// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Internal.proto
// Protobuf C++ Version: 6.33.4

#ifndef Internal_2eproto_2epb_2eh
#define Internal_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Internal_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Internal_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Internal_2eproto;
}  // extern "C"
namespace match {
class GamePacket;
struct GamePacketDefaultTypeInternal;
extern GamePacketDefaultTypeInternal _GamePacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GamePacket_class_data_;
class MatchCreateRequest;
struct MatchCreateRequestDefaultTypeInternal;
extern MatchCreateRequestDefaultTypeInternal _MatchCreateRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MatchCreateRequest_class_data_;
class MatchCreateResponse;
struct MatchCreateResponseDefaultTypeInternal;
extern MatchCreateResponseDefaultTypeInternal _MatchCreateResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MatchCreateResponse_class_data_;
class UserSessionInfo;
struct UserSessionInfoDefaultTypeInternal;
extern UserSessionInfoDefaultTypeInternal _UserSessionInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UserSessionInfo_class_data_;
}  // namespace match
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace match {

// ===================================================================


// -------------------------------------------------------------------

class UserSessionInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:match.UserSessionInfo) */ {
 public:
  inline UserSessionInfo() : UserSessionInfo(nullptr) {}
  ~UserSessionInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UserSessionInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UserSessionInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UserSessionInfo(::google::protobuf::internal::ConstantInitialized);

  inline UserSessionInfo(const UserSessionInfo& from) : UserSessionInfo(nullptr, from) {}
  inline UserSessionInfo(UserSessionInfo&& from) noexcept
      : UserSessionInfo(nullptr, ::std::move(from)) {}
  inline UserSessionInfo& operator=(const UserSessionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserSessionInfo& operator=(UserSessionInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserSessionInfo& default_instance() {
    return *reinterpret_cast<const UserSessionInfo*>(
        &_UserSessionInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(UserSessionInfo& a, UserSessionInfo& b) { a.Swap(&b); }
  inline void Swap(UserSessionInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserSessionInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserSessionInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UserSessionInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UserSessionInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UserSessionInfo& from) { UserSessionInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UserSessionInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "match.UserSessionInfo"; }

  explicit UserSessionInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UserSessionInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UserSessionInfo& from);
  UserSessionInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UserSessionInfo&& from) noexcept
      : UserSessionInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
    kSessionTokenFieldNumber = 2,
  };
  // string user_id = 1;
  void clear_user_id() ;
  const ::std::string& user_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_user_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_user_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_user_id();
  void set_allocated_user_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_user_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_user_id();

  public:
  // string session_token = 2;
  void clear_session_token() ;
  const ::std::string& session_token() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_token(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_token();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_token();
  void set_allocated_session_token(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_token() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_token(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_token();

  public:
  // @@protoc_insertion_point(class_scope:match.UserSessionInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 50,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UserSessionInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr user_id_;
    ::google::protobuf::internal::ArenaStringPtr session_token_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Internal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UserSessionInfo_class_data_;
// -------------------------------------------------------------------

class MatchCreateResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:match.MatchCreateResponse) */ {
 public:
  inline MatchCreateResponse() : MatchCreateResponse(nullptr) {}
  ~MatchCreateResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MatchCreateResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MatchCreateResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MatchCreateResponse(::google::protobuf::internal::ConstantInitialized);

  inline MatchCreateResponse(const MatchCreateResponse& from) : MatchCreateResponse(nullptr, from) {}
  inline MatchCreateResponse(MatchCreateResponse&& from) noexcept
      : MatchCreateResponse(nullptr, ::std::move(from)) {}
  inline MatchCreateResponse& operator=(const MatchCreateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatchCreateResponse& operator=(MatchCreateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatchCreateResponse& default_instance() {
    return *reinterpret_cast<const MatchCreateResponse*>(
        &_MatchCreateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(MatchCreateResponse& a, MatchCreateResponse& b) { a.Swap(&b); }
  inline void Swap(MatchCreateResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatchCreateResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatchCreateResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MatchCreateResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MatchCreateResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MatchCreateResponse& from) { MatchCreateResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MatchCreateResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "match.MatchCreateResponse"; }

  explicit MatchCreateResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MatchCreateResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MatchCreateResponse& from);
  MatchCreateResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MatchCreateResponse&& from) noexcept
      : MatchCreateResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMatchIdFieldNumber = 1,
    kServerIpFieldNumber = 4,
    kErrorMessageFieldNumber = 5,
    kSuccessFieldNumber = 2,
    kPortFieldNumber = 3,
  };
  // string match_id = 1;
  void clear_match_id() ;
  const ::std::string& match_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_match_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_match_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_match_id();
  void set_allocated_match_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_match_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_match_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_match_id();

  public:
  // string server_ip = 4;
  void clear_server_ip() ;
  const ::std::string& server_ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_server_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_server_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_server_ip();
  void set_allocated_server_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_server_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_server_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_server_ip();

  public:
  // string error_message = 5;
  void clear_error_message() ;
  const ::std::string& error_message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_error_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_error_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_error_message();
  void set_allocated_error_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_error_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_error_message();

  public:
  // bool success = 2;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // int32 port = 3;
  void clear_port() ;
  ::int32_t port() const;
  void set_port(::int32_t value);

  private:
  ::int32_t _internal_port() const;
  void _internal_set_port(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:match.MatchCreateResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 64,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MatchCreateResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr match_id_;
    ::google::protobuf::internal::ArenaStringPtr server_ip_;
    ::google::protobuf::internal::ArenaStringPtr error_message_;
    bool success_;
    ::int32_t port_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Internal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MatchCreateResponse_class_data_;
// -------------------------------------------------------------------

class MatchCreateRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:match.MatchCreateRequest) */ {
 public:
  inline MatchCreateRequest() : MatchCreateRequest(nullptr) {}
  ~MatchCreateRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MatchCreateRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MatchCreateRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MatchCreateRequest(::google::protobuf::internal::ConstantInitialized);

  inline MatchCreateRequest(const MatchCreateRequest& from) : MatchCreateRequest(nullptr, from) {}
  inline MatchCreateRequest(MatchCreateRequest&& from) noexcept
      : MatchCreateRequest(nullptr, ::std::move(from)) {}
  inline MatchCreateRequest& operator=(const MatchCreateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatchCreateRequest& operator=(MatchCreateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatchCreateRequest& default_instance() {
    return *reinterpret_cast<const MatchCreateRequest*>(
        &_MatchCreateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MatchCreateRequest& a, MatchCreateRequest& b) { a.Swap(&b); }
  inline void Swap(MatchCreateRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatchCreateRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatchCreateRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MatchCreateRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MatchCreateRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MatchCreateRequest& from) { MatchCreateRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MatchCreateRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "match.MatchCreateRequest"; }

  explicit MatchCreateRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MatchCreateRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MatchCreateRequest& from);
  MatchCreateRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MatchCreateRequest&& from) noexcept
      : MatchCreateRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUsersFieldNumber = 3,
    kMatchIdFieldNumber = 1,
    kGameTypeFieldNumber = 2,
  };
  // repeated .match.UserSessionInfo users = 3;
  int users_size() const;
  private:
  int _internal_users_size() const;

  public:
  void clear_users() ;
  ::match::UserSessionInfo* PROTOBUF_NONNULL mutable_users(int index);
  ::google::protobuf::RepeatedPtrField<::match::UserSessionInfo>* PROTOBUF_NONNULL mutable_users();

  private:
  const ::google::protobuf::RepeatedPtrField<::match::UserSessionInfo>& _internal_users() const;
  ::google::protobuf::RepeatedPtrField<::match::UserSessionInfo>* PROTOBUF_NONNULL _internal_mutable_users();
  public:
  const ::match::UserSessionInfo& users(int index) const;
  ::match::UserSessionInfo* PROTOBUF_NONNULL add_users();
  const ::google::protobuf::RepeatedPtrField<::match::UserSessionInfo>& users() const;
  // string match_id = 1;
  void clear_match_id() ;
  const ::std::string& match_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_match_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_match_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_match_id();
  void set_allocated_match_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_match_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_match_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_match_id();

  public:
  // string game_type = 2;
  void clear_game_type() ;
  const ::std::string& game_type() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_game_type(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_game_type();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_game_type();
  void set_allocated_game_type(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_game_type() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_game_type(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_game_type();

  public:
  // @@protoc_insertion_point(class_scope:match.MatchCreateRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 50,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MatchCreateRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::match::UserSessionInfo > users_;
    ::google::protobuf::internal::ArenaStringPtr match_id_;
    ::google::protobuf::internal::ArenaStringPtr game_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Internal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MatchCreateRequest_class_data_;
// -------------------------------------------------------------------

class GamePacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:match.GamePacket) */ {
 public:
  inline GamePacket() : GamePacket(nullptr) {}
  ~GamePacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GamePacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GamePacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GamePacket(::google::protobuf::internal::ConstantInitialized);

  inline GamePacket(const GamePacket& from) : GamePacket(nullptr, from) {}
  inline GamePacket(GamePacket&& from) noexcept
      : GamePacket(nullptr, ::std::move(from)) {}
  inline GamePacket& operator=(const GamePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline GamePacket& operator=(GamePacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GamePacket& default_instance() {
    return *reinterpret_cast<const GamePacket*>(
        &_GamePacket_default_instance_);
  }
  enum PayloadCase {
    kMatchCreateReq = 10,
    kMatchCreateRes = 11,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GamePacket& a, GamePacket& b) { a.Swap(&b); }
  inline void Swap(GamePacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GamePacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GamePacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GamePacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GamePacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GamePacket& from) { GamePacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GamePacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "match.GamePacket"; }

  explicit GamePacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GamePacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GamePacket& from);
  GamePacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GamePacket&& from) noexcept
      : GamePacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSequenceIdFieldNumber = 1,
    kMatchCreateReqFieldNumber = 10,
    kMatchCreateResFieldNumber = 11,
  };
  // uint32 sequence_id = 1;
  void clear_sequence_id() ;
  ::uint32_t sequence_id() const;
  void set_sequence_id(::uint32_t value);

  private:
  ::uint32_t _internal_sequence_id() const;
  void _internal_set_sequence_id(::uint32_t value);

  public:
  // .match.MatchCreateRequest match_create_req = 10;
  bool has_match_create_req() const;
  private:
  bool _internal_has_match_create_req() const;

  public:
  void clear_match_create_req() ;
  const ::match::MatchCreateRequest& match_create_req() const;
  [[nodiscard]] ::match::MatchCreateRequest* PROTOBUF_NULLABLE release_match_create_req();
  ::match::MatchCreateRequest* PROTOBUF_NONNULL mutable_match_create_req();
  void set_allocated_match_create_req(::match::MatchCreateRequest* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_match_create_req(::match::MatchCreateRequest* PROTOBUF_NULLABLE value);
  ::match::MatchCreateRequest* PROTOBUF_NULLABLE unsafe_arena_release_match_create_req();

  private:
  const ::match::MatchCreateRequest& _internal_match_create_req() const;
  ::match::MatchCreateRequest* PROTOBUF_NONNULL _internal_mutable_match_create_req();

  public:
  // .match.MatchCreateResponse match_create_res = 11;
  bool has_match_create_res() const;
  private:
  bool _internal_has_match_create_res() const;

  public:
  void clear_match_create_res() ;
  const ::match::MatchCreateResponse& match_create_res() const;
  [[nodiscard]] ::match::MatchCreateResponse* PROTOBUF_NULLABLE release_match_create_res();
  ::match::MatchCreateResponse* PROTOBUF_NONNULL mutable_match_create_res();
  void set_allocated_match_create_res(::match::MatchCreateResponse* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_match_create_res(::match::MatchCreateResponse* PROTOBUF_NULLABLE value);
  ::match::MatchCreateResponse* PROTOBUF_NULLABLE unsafe_arena_release_match_create_res();

  private:
  const ::match::MatchCreateResponse& _internal_match_create_res() const;
  ::match::MatchCreateResponse* PROTOBUF_NONNULL _internal_mutable_match_create_res();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:match.GamePacket)
 private:
  class _Internal;
  void set_has_match_create_req();
  void set_has_match_create_res();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 3,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GamePacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t sequence_id_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::match::MatchCreateRequest* PROTOBUF_NULLABLE match_create_req_;
      ::match::MatchCreateResponse* PROTOBUF_NULLABLE match_create_res_;
    } payload_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Internal_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GamePacket_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GamePacket

// uint32 sequence_id = 1;
inline void GamePacket::clear_sequence_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t GamePacket::sequence_id() const {
  // @@protoc_insertion_point(field_get:match.GamePacket.sequence_id)
  return _internal_sequence_id();
}
inline void GamePacket::set_sequence_id(::uint32_t value) {
  _internal_set_sequence_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:match.GamePacket.sequence_id)
}
inline ::uint32_t GamePacket::_internal_sequence_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequence_id_;
}
inline void GamePacket::_internal_set_sequence_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_id_ = value;
}

// .match.MatchCreateRequest match_create_req = 10;
inline bool GamePacket::has_match_create_req() const {
  return payload_case() == kMatchCreateReq;
}
inline bool GamePacket::_internal_has_match_create_req() const {
  return payload_case() == kMatchCreateReq;
}
inline void GamePacket::set_has_match_create_req() {
  _impl_._oneof_case_[0] = kMatchCreateReq;
}
inline void GamePacket::clear_match_create_req() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMatchCreateReq) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.match_create_req_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.match_create_req_);
    }
    clear_has_payload();
  }
}
inline ::match::MatchCreateRequest* PROTOBUF_NULLABLE GamePacket::release_match_create_req() {
  // @@protoc_insertion_point(field_release:match.GamePacket.match_create_req)
  if (payload_case() == kMatchCreateReq) {
    clear_has_payload();
    auto* temp = _impl_.payload_.match_create_req_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.match_create_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::match::MatchCreateRequest& GamePacket::_internal_match_create_req() const {
  return payload_case() == kMatchCreateReq ? static_cast<const ::match::MatchCreateRequest&>(*_impl_.payload_.match_create_req_)
                     : reinterpret_cast<const ::match::MatchCreateRequest&>(::match::_MatchCreateRequest_default_instance_);
}
inline const ::match::MatchCreateRequest& GamePacket::match_create_req() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.GamePacket.match_create_req)
  return _internal_match_create_req();
}
inline ::match::MatchCreateRequest* PROTOBUF_NULLABLE GamePacket::unsafe_arena_release_match_create_req() {
  // @@protoc_insertion_point(field_unsafe_arena_release:match.GamePacket.match_create_req)
  if (payload_case() == kMatchCreateReq) {
    clear_has_payload();
    auto* temp = _impl_.payload_.match_create_req_;
    _impl_.payload_.match_create_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GamePacket::unsafe_arena_set_allocated_match_create_req(
    ::match::MatchCreateRequest* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_match_create_req();
    _impl_.payload_.match_create_req_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:match.GamePacket.match_create_req)
}
inline ::match::MatchCreateRequest* PROTOBUF_NONNULL GamePacket::_internal_mutable_match_create_req() {
  if (payload_case() != kMatchCreateReq) {
    clear_payload();
    set_has_match_create_req();
    _impl_.payload_.match_create_req_ = 
        ::google::protobuf::Message::DefaultConstruct<::match::MatchCreateRequest>(GetArena());
  }
  return _impl_.payload_.match_create_req_;
}
inline ::match::MatchCreateRequest* PROTOBUF_NONNULL GamePacket::mutable_match_create_req()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::match::MatchCreateRequest* _msg = _internal_mutable_match_create_req();
  // @@protoc_insertion_point(field_mutable:match.GamePacket.match_create_req)
  return _msg;
}

// .match.MatchCreateResponse match_create_res = 11;
inline bool GamePacket::has_match_create_res() const {
  return payload_case() == kMatchCreateRes;
}
inline bool GamePacket::_internal_has_match_create_res() const {
  return payload_case() == kMatchCreateRes;
}
inline void GamePacket::set_has_match_create_res() {
  _impl_._oneof_case_[0] = kMatchCreateRes;
}
inline void GamePacket::clear_match_create_res() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMatchCreateRes) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.match_create_res_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.match_create_res_);
    }
    clear_has_payload();
  }
}
inline ::match::MatchCreateResponse* PROTOBUF_NULLABLE GamePacket::release_match_create_res() {
  // @@protoc_insertion_point(field_release:match.GamePacket.match_create_res)
  if (payload_case() == kMatchCreateRes) {
    clear_has_payload();
    auto* temp = _impl_.payload_.match_create_res_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.match_create_res_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::match::MatchCreateResponse& GamePacket::_internal_match_create_res() const {
  return payload_case() == kMatchCreateRes ? static_cast<const ::match::MatchCreateResponse&>(*_impl_.payload_.match_create_res_)
                     : reinterpret_cast<const ::match::MatchCreateResponse&>(::match::_MatchCreateResponse_default_instance_);
}
inline const ::match::MatchCreateResponse& GamePacket::match_create_res() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.GamePacket.match_create_res)
  return _internal_match_create_res();
}
inline ::match::MatchCreateResponse* PROTOBUF_NULLABLE GamePacket::unsafe_arena_release_match_create_res() {
  // @@protoc_insertion_point(field_unsafe_arena_release:match.GamePacket.match_create_res)
  if (payload_case() == kMatchCreateRes) {
    clear_has_payload();
    auto* temp = _impl_.payload_.match_create_res_;
    _impl_.payload_.match_create_res_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GamePacket::unsafe_arena_set_allocated_match_create_res(
    ::match::MatchCreateResponse* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_match_create_res();
    _impl_.payload_.match_create_res_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:match.GamePacket.match_create_res)
}
inline ::match::MatchCreateResponse* PROTOBUF_NONNULL GamePacket::_internal_mutable_match_create_res() {
  if (payload_case() != kMatchCreateRes) {
    clear_payload();
    set_has_match_create_res();
    _impl_.payload_.match_create_res_ = 
        ::google::protobuf::Message::DefaultConstruct<::match::MatchCreateResponse>(GetArena());
  }
  return _impl_.payload_.match_create_res_;
}
inline ::match::MatchCreateResponse* PROTOBUF_NONNULL GamePacket::mutable_match_create_res()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::match::MatchCreateResponse* _msg = _internal_mutable_match_create_res();
  // @@protoc_insertion_point(field_mutable:match.GamePacket.match_create_res)
  return _msg;
}

inline bool GamePacket::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void GamePacket::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline GamePacket::PayloadCase GamePacket::payload_case() const {
  return GamePacket::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// UserSessionInfo

// string user_id = 1;
inline void UserSessionInfo::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& UserSessionInfo::user_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.UserSessionInfo.user_id)
  return _internal_user_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void UserSessionInfo::set_user_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.user_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:match.UserSessionInfo.user_id)
}
inline ::std::string* PROTOBUF_NONNULL UserSessionInfo::mutable_user_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:match.UserSessionInfo.user_id)
  return _s;
}
inline const ::std::string& UserSessionInfo::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_.Get();
}
inline void UserSessionInfo::_internal_set_user_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL UserSessionInfo::_internal_mutable_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.user_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE UserSessionInfo::release_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:match.UserSessionInfo.user_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.user_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.user_id_.Set("", GetArena());
  }
  return released;
}
inline void UserSessionInfo::set_allocated_user_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.user_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:match.UserSessionInfo.user_id)
}

// string session_token = 2;
inline void UserSessionInfo::clear_session_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_token_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& UserSessionInfo::session_token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.UserSessionInfo.session_token)
  return _internal_session_token();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void UserSessionInfo::set_session_token(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.session_token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:match.UserSessionInfo.session_token)
}
inline ::std::string* PROTOBUF_NONNULL UserSessionInfo::mutable_session_token()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_session_token();
  // @@protoc_insertion_point(field_mutable:match.UserSessionInfo.session_token)
  return _s;
}
inline const ::std::string& UserSessionInfo::_internal_session_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_token_.Get();
}
inline void UserSessionInfo::_internal_set_session_token(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_token_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL UserSessionInfo::_internal_mutable_session_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_token_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE UserSessionInfo::release_session_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:match.UserSessionInfo.session_token)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.session_token_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_token_.Set("", GetArena());
  }
  return released;
}
inline void UserSessionInfo::set_allocated_session_token(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.session_token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_token_.IsDefault()) {
    _impl_.session_token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:match.UserSessionInfo.session_token)
}

// -------------------------------------------------------------------

// MatchCreateRequest

// string match_id = 1;
inline void MatchCreateRequest::clear_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& MatchCreateRequest::match_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.MatchCreateRequest.match_id)
  return _internal_match_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MatchCreateRequest::set_match_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.match_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:match.MatchCreateRequest.match_id)
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateRequest::mutable_match_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_match_id();
  // @@protoc_insertion_point(field_mutable:match.MatchCreateRequest.match_id)
  return _s;
}
inline const ::std::string& MatchCreateRequest::_internal_match_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.match_id_.Get();
}
inline void MatchCreateRequest::_internal_set_match_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateRequest::_internal_mutable_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.match_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MatchCreateRequest::release_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:match.MatchCreateRequest.match_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.match_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.match_id_.Set("", GetArena());
  }
  return released;
}
inline void MatchCreateRequest::set_allocated_match_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.match_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.match_id_.IsDefault()) {
    _impl_.match_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:match.MatchCreateRequest.match_id)
}

// string game_type = 2;
inline void MatchCreateRequest::clear_game_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_type_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& MatchCreateRequest::game_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.MatchCreateRequest.game_type)
  return _internal_game_type();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MatchCreateRequest::set_game_type(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.game_type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:match.MatchCreateRequest.game_type)
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateRequest::mutable_game_type()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_game_type();
  // @@protoc_insertion_point(field_mutable:match.MatchCreateRequest.game_type)
  return _s;
}
inline const ::std::string& MatchCreateRequest::_internal_game_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.game_type_.Get();
}
inline void MatchCreateRequest::_internal_set_game_type(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_type_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateRequest::_internal_mutable_game_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.game_type_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MatchCreateRequest::release_game_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:match.MatchCreateRequest.game_type)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.game_type_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.game_type_.Set("", GetArena());
  }
  return released;
}
inline void MatchCreateRequest::set_allocated_game_type(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.game_type_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.game_type_.IsDefault()) {
    _impl_.game_type_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:match.MatchCreateRequest.game_type)
}

// repeated .match.UserSessionInfo users = 3;
inline int MatchCreateRequest::_internal_users_size() const {
  return _internal_users().size();
}
inline int MatchCreateRequest::users_size() const {
  return _internal_users_size();
}
inline void MatchCreateRequest::clear_users() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.users_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::match::UserSessionInfo* PROTOBUF_NONNULL MatchCreateRequest::mutable_users(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:match.MatchCreateRequest.users)
  return _internal_mutable_users()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::match::UserSessionInfo>* PROTOBUF_NONNULL MatchCreateRequest::mutable_users()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:match.MatchCreateRequest.users)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_users();
}
inline const ::match::UserSessionInfo& MatchCreateRequest::users(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.MatchCreateRequest.users)
  return _internal_users().Get(index);
}
inline ::match::UserSessionInfo* PROTOBUF_NONNULL MatchCreateRequest::add_users()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::match::UserSessionInfo* _add =
      _internal_mutable_users()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:match.MatchCreateRequest.users)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::match::UserSessionInfo>& MatchCreateRequest::users() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:match.MatchCreateRequest.users)
  return _internal_users();
}
inline const ::google::protobuf::RepeatedPtrField<::match::UserSessionInfo>&
MatchCreateRequest::_internal_users() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.users_;
}
inline ::google::protobuf::RepeatedPtrField<::match::UserSessionInfo>* PROTOBUF_NONNULL
MatchCreateRequest::_internal_mutable_users() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.users_;
}

// -------------------------------------------------------------------

// MatchCreateResponse

// string match_id = 1;
inline void MatchCreateResponse::clear_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& MatchCreateResponse::match_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.MatchCreateResponse.match_id)
  return _internal_match_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MatchCreateResponse::set_match_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.match_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:match.MatchCreateResponse.match_id)
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateResponse::mutable_match_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_match_id();
  // @@protoc_insertion_point(field_mutable:match.MatchCreateResponse.match_id)
  return _s;
}
inline const ::std::string& MatchCreateResponse::_internal_match_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.match_id_.Get();
}
inline void MatchCreateResponse::_internal_set_match_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateResponse::_internal_mutable_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.match_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MatchCreateResponse::release_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:match.MatchCreateResponse.match_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.match_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.match_id_.Set("", GetArena());
  }
  return released;
}
inline void MatchCreateResponse::set_allocated_match_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.match_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.match_id_.IsDefault()) {
    _impl_.match_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:match.MatchCreateResponse.match_id)
}

// bool success = 2;
inline void MatchCreateResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool MatchCreateResponse::success() const {
  // @@protoc_insertion_point(field_get:match.MatchCreateResponse.success)
  return _internal_success();
}
inline void MatchCreateResponse::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:match.MatchCreateResponse.success)
}
inline bool MatchCreateResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void MatchCreateResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// int32 port = 3;
inline void MatchCreateResponse::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t MatchCreateResponse::port() const {
  // @@protoc_insertion_point(field_get:match.MatchCreateResponse.port)
  return _internal_port();
}
inline void MatchCreateResponse::set_port(::int32_t value) {
  _internal_set_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:match.MatchCreateResponse.port)
}
inline ::int32_t MatchCreateResponse::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void MatchCreateResponse::_internal_set_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// string server_ip = 4;
inline void MatchCreateResponse::clear_server_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& MatchCreateResponse::server_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.MatchCreateResponse.server_ip)
  return _internal_server_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MatchCreateResponse::set_server_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.server_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:match.MatchCreateResponse.server_ip)
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateResponse::mutable_server_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_server_ip();
  // @@protoc_insertion_point(field_mutable:match.MatchCreateResponse.server_ip)
  return _s;
}
inline const ::std::string& MatchCreateResponse::_internal_server_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_ip_.Get();
}
inline void MatchCreateResponse::_internal_set_server_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateResponse::_internal_mutable_server_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.server_ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MatchCreateResponse::release_server_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:match.MatchCreateResponse.server_ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.server_ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.server_ip_.Set("", GetArena());
  }
  return released;
}
inline void MatchCreateResponse::set_allocated_server_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.server_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.server_ip_.IsDefault()) {
    _impl_.server_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:match.MatchCreateResponse.server_ip)
}

// string error_message = 5;
inline void MatchCreateResponse::clear_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& MatchCreateResponse::error_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:match.MatchCreateResponse.error_message)
  return _internal_error_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MatchCreateResponse::set_error_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.error_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:match.MatchCreateResponse.error_message)
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateResponse::mutable_error_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:match.MatchCreateResponse.error_message)
  return _s;
}
inline const ::std::string& MatchCreateResponse::_internal_error_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_message_.Get();
}
inline void MatchCreateResponse::_internal_set_error_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MatchCreateResponse::_internal_mutable_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.error_message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MatchCreateResponse::release_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:match.MatchCreateResponse.error_message)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.error_message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.error_message_.Set("", GetArena());
  }
  return released;
}
inline void MatchCreateResponse::set_allocated_error_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.error_message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:match.MatchCreateResponse.error_message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace match


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Internal_2eproto_2epb_2eh
