// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Internal.proto
// Protobuf C++ Version: 5.29.5

#ifndef Internal_2eproto_2epb_2eh
#define Internal_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Internal_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Internal_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Internal_2eproto;
namespace Internal {
class GamePacket;
struct GamePacketDefaultTypeInternal;
extern GamePacketDefaultTypeInternal _GamePacket_default_instance_;
class MatchCreateRequest;
struct MatchCreateRequestDefaultTypeInternal;
extern MatchCreateRequestDefaultTypeInternal _MatchCreateRequest_default_instance_;
class MatchCreateResponse;
struct MatchCreateResponseDefaultTypeInternal;
extern MatchCreateResponseDefaultTypeInternal _MatchCreateResponse_default_instance_;
class UserSessionInfo;
struct UserSessionInfoDefaultTypeInternal;
extern UserSessionInfoDefaultTypeInternal _UserSessionInfo_default_instance_;
}  // namespace Internal
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Internal {

// ===================================================================


// -------------------------------------------------------------------

class UserSessionInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Internal.UserSessionInfo) */ {
 public:
  inline UserSessionInfo() : UserSessionInfo(nullptr) {}
  ~UserSessionInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UserSessionInfo* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UserSessionInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UserSessionInfo(
      ::google::protobuf::internal::ConstantInitialized);

  inline UserSessionInfo(const UserSessionInfo& from) : UserSessionInfo(nullptr, from) {}
  inline UserSessionInfo(UserSessionInfo&& from) noexcept
      : UserSessionInfo(nullptr, std::move(from)) {}
  inline UserSessionInfo& operator=(const UserSessionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserSessionInfo& operator=(UserSessionInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserSessionInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserSessionInfo* internal_default_instance() {
    return reinterpret_cast<const UserSessionInfo*>(
        &_UserSessionInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(UserSessionInfo& a, UserSessionInfo& b) { a.Swap(&b); }
  inline void Swap(UserSessionInfo* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserSessionInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserSessionInfo* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UserSessionInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UserSessionInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UserSessionInfo& from) { UserSessionInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UserSessionInfo* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Internal.UserSessionInfo"; }

 protected:
  explicit UserSessionInfo(::google::protobuf::Arena* arena);
  UserSessionInfo(::google::protobuf::Arena* arena, const UserSessionInfo& from);
  UserSessionInfo(::google::protobuf::Arena* arena, UserSessionInfo&& from) noexcept
      : UserSessionInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
    kSessionTokenFieldNumber = 2,
  };
  // string user_id = 1;
  void clear_user_id() ;
  const std::string& user_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_user_id(Arg_&& arg, Args_... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* value);

  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(
      const std::string& value);
  std::string* _internal_mutable_user_id();

  public:
  // string session_token = 2;
  void clear_session_token() ;
  const std::string& session_token() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_session_token(Arg_&& arg, Args_... args);
  std::string* mutable_session_token();
  PROTOBUF_NODISCARD std::string* release_session_token();
  void set_allocated_session_token(std::string* value);

  private:
  const std::string& _internal_session_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_token(
      const std::string& value);
  std::string* _internal_mutable_session_token();

  public:
  // @@protoc_insertion_point(class_scope:Internal.UserSessionInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      53, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UserSessionInfo& from_msg);
    ::google::protobuf::internal::ArenaStringPtr user_id_;
    ::google::protobuf::internal::ArenaStringPtr session_token_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Internal_2eproto;
};
// -------------------------------------------------------------------

class MatchCreateResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Internal.MatchCreateResponse) */ {
 public:
  inline MatchCreateResponse() : MatchCreateResponse(nullptr) {}
  ~MatchCreateResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MatchCreateResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MatchCreateResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MatchCreateResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline MatchCreateResponse(const MatchCreateResponse& from) : MatchCreateResponse(nullptr, from) {}
  inline MatchCreateResponse(MatchCreateResponse&& from) noexcept
      : MatchCreateResponse(nullptr, std::move(from)) {}
  inline MatchCreateResponse& operator=(const MatchCreateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatchCreateResponse& operator=(MatchCreateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatchCreateResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const MatchCreateResponse* internal_default_instance() {
    return reinterpret_cast<const MatchCreateResponse*>(
        &_MatchCreateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(MatchCreateResponse& a, MatchCreateResponse& b) { a.Swap(&b); }
  inline void Swap(MatchCreateResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatchCreateResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatchCreateResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MatchCreateResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MatchCreateResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MatchCreateResponse& from) { MatchCreateResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MatchCreateResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Internal.MatchCreateResponse"; }

 protected:
  explicit MatchCreateResponse(::google::protobuf::Arena* arena);
  MatchCreateResponse(::google::protobuf::Arena* arena, const MatchCreateResponse& from);
  MatchCreateResponse(::google::protobuf::Arena* arena, MatchCreateResponse&& from) noexcept
      : MatchCreateResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMatchIdFieldNumber = 1,
    kServerIpFieldNumber = 4,
    kErrorMessageFieldNumber = 5,
    kSuccessFieldNumber = 2,
    kPortFieldNumber = 3,
  };
  // string match_id = 1;
  void clear_match_id() ;
  const std::string& match_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_match_id(Arg_&& arg, Args_... args);
  std::string* mutable_match_id();
  PROTOBUF_NODISCARD std::string* release_match_id();
  void set_allocated_match_id(std::string* value);

  private:
  const std::string& _internal_match_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_match_id(
      const std::string& value);
  std::string* _internal_mutable_match_id();

  public:
  // string server_ip = 4;
  void clear_server_ip() ;
  const std::string& server_ip() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_server_ip(Arg_&& arg, Args_... args);
  std::string* mutable_server_ip();
  PROTOBUF_NODISCARD std::string* release_server_ip();
  void set_allocated_server_ip(std::string* value);

  private:
  const std::string& _internal_server_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_ip(
      const std::string& value);
  std::string* _internal_mutable_server_ip();

  public:
  // string error_message = 5;
  void clear_error_message() ;
  const std::string& error_message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_error_message(Arg_&& arg, Args_... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* value);

  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(
      const std::string& value);
  std::string* _internal_mutable_error_message();

  public:
  // bool success = 2;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // int32 port = 3;
  void clear_port() ;
  ::int32_t port() const;
  void set_port(::int32_t value);

  private:
  ::int32_t _internal_port() const;
  void _internal_set_port(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Internal.MatchCreateResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      67, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MatchCreateResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr match_id_;
    ::google::protobuf::internal::ArenaStringPtr server_ip_;
    ::google::protobuf::internal::ArenaStringPtr error_message_;
    bool success_;
    ::int32_t port_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Internal_2eproto;
};
// -------------------------------------------------------------------

class MatchCreateRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Internal.MatchCreateRequest) */ {
 public:
  inline MatchCreateRequest() : MatchCreateRequest(nullptr) {}
  ~MatchCreateRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MatchCreateRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MatchCreateRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MatchCreateRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline MatchCreateRequest(const MatchCreateRequest& from) : MatchCreateRequest(nullptr, from) {}
  inline MatchCreateRequest(MatchCreateRequest&& from) noexcept
      : MatchCreateRequest(nullptr, std::move(from)) {}
  inline MatchCreateRequest& operator=(const MatchCreateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatchCreateRequest& operator=(MatchCreateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatchCreateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MatchCreateRequest* internal_default_instance() {
    return reinterpret_cast<const MatchCreateRequest*>(
        &_MatchCreateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MatchCreateRequest& a, MatchCreateRequest& b) { a.Swap(&b); }
  inline void Swap(MatchCreateRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatchCreateRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatchCreateRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MatchCreateRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MatchCreateRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MatchCreateRequest& from) { MatchCreateRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MatchCreateRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Internal.MatchCreateRequest"; }

 protected:
  explicit MatchCreateRequest(::google::protobuf::Arena* arena);
  MatchCreateRequest(::google::protobuf::Arena* arena, const MatchCreateRequest& from);
  MatchCreateRequest(::google::protobuf::Arena* arena, MatchCreateRequest&& from) noexcept
      : MatchCreateRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUsersFieldNumber = 3,
    kMatchIdFieldNumber = 1,
    kGameTypeFieldNumber = 2,
  };
  // repeated .Internal.UserSessionInfo users = 3;
  int users_size() const;
  private:
  int _internal_users_size() const;

  public:
  void clear_users() ;
  ::Internal::UserSessionInfo* mutable_users(int index);
  ::google::protobuf::RepeatedPtrField<::Internal::UserSessionInfo>* mutable_users();

  private:
  const ::google::protobuf::RepeatedPtrField<::Internal::UserSessionInfo>& _internal_users() const;
  ::google::protobuf::RepeatedPtrField<::Internal::UserSessionInfo>* _internal_mutable_users();
  public:
  const ::Internal::UserSessionInfo& users(int index) const;
  ::Internal::UserSessionInfo* add_users();
  const ::google::protobuf::RepeatedPtrField<::Internal::UserSessionInfo>& users() const;
  // string match_id = 1;
  void clear_match_id() ;
  const std::string& match_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_match_id(Arg_&& arg, Args_... args);
  std::string* mutable_match_id();
  PROTOBUF_NODISCARD std::string* release_match_id();
  void set_allocated_match_id(std::string* value);

  private:
  const std::string& _internal_match_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_match_id(
      const std::string& value);
  std::string* _internal_mutable_match_id();

  public:
  // string game_type = 2;
  void clear_game_type() ;
  const std::string& game_type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_game_type(Arg_&& arg, Args_... args);
  std::string* mutable_game_type();
  PROTOBUF_NODISCARD std::string* release_game_type();
  void set_allocated_game_type(std::string* value);

  private:
  const std::string& _internal_game_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_game_type(
      const std::string& value);
  std::string* _internal_mutable_game_type();

  public:
  // @@protoc_insertion_point(class_scope:Internal.MatchCreateRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      53, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MatchCreateRequest& from_msg);
    ::google::protobuf::RepeatedPtrField< ::Internal::UserSessionInfo > users_;
    ::google::protobuf::internal::ArenaStringPtr match_id_;
    ::google::protobuf::internal::ArenaStringPtr game_type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Internal_2eproto;
};
// -------------------------------------------------------------------

class GamePacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Internal.GamePacket) */ {
 public:
  inline GamePacket() : GamePacket(nullptr) {}
  ~GamePacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GamePacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GamePacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GamePacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline GamePacket(const GamePacket& from) : GamePacket(nullptr, from) {}
  inline GamePacket(GamePacket&& from) noexcept
      : GamePacket(nullptr, std::move(from)) {}
  inline GamePacket& operator=(const GamePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline GamePacket& operator=(GamePacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GamePacket& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kMatchCreateReq = 10,
    kMatchCreateRes = 11,
    PAYLOAD_NOT_SET = 0,
  };
  static inline const GamePacket* internal_default_instance() {
    return reinterpret_cast<const GamePacket*>(
        &_GamePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GamePacket& a, GamePacket& b) { a.Swap(&b); }
  inline void Swap(GamePacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GamePacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GamePacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GamePacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GamePacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GamePacket& from) { GamePacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GamePacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Internal.GamePacket"; }

 protected:
  explicit GamePacket(::google::protobuf::Arena* arena);
  GamePacket(::google::protobuf::Arena* arena, const GamePacket& from);
  GamePacket(::google::protobuf::Arena* arena, GamePacket&& from) noexcept
      : GamePacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSequenceIdFieldNumber = 1,
    kMatchCreateReqFieldNumber = 10,
    kMatchCreateResFieldNumber = 11,
  };
  // uint32 sequence_id = 1;
  void clear_sequence_id() ;
  ::uint32_t sequence_id() const;
  void set_sequence_id(::uint32_t value);

  private:
  ::uint32_t _internal_sequence_id() const;
  void _internal_set_sequence_id(::uint32_t value);

  public:
  // .Internal.MatchCreateRequest match_create_req = 10;
  bool has_match_create_req() const;
  private:
  bool _internal_has_match_create_req() const;

  public:
  void clear_match_create_req() ;
  const ::Internal::MatchCreateRequest& match_create_req() const;
  PROTOBUF_NODISCARD ::Internal::MatchCreateRequest* release_match_create_req();
  ::Internal::MatchCreateRequest* mutable_match_create_req();
  void set_allocated_match_create_req(::Internal::MatchCreateRequest* value);
  void unsafe_arena_set_allocated_match_create_req(::Internal::MatchCreateRequest* value);
  ::Internal::MatchCreateRequest* unsafe_arena_release_match_create_req();

  private:
  const ::Internal::MatchCreateRequest& _internal_match_create_req() const;
  ::Internal::MatchCreateRequest* _internal_mutable_match_create_req();

  public:
  // .Internal.MatchCreateResponse match_create_res = 11;
  bool has_match_create_res() const;
  private:
  bool _internal_has_match_create_res() const;

  public:
  void clear_match_create_res() ;
  const ::Internal::MatchCreateResponse& match_create_res() const;
  PROTOBUF_NODISCARD ::Internal::MatchCreateResponse* release_match_create_res();
  ::Internal::MatchCreateResponse* mutable_match_create_res();
  void set_allocated_match_create_res(::Internal::MatchCreateResponse* value);
  void unsafe_arena_set_allocated_match_create_res(::Internal::MatchCreateResponse* value);
  ::Internal::MatchCreateResponse* unsafe_arena_release_match_create_res();

  private:
  const ::Internal::MatchCreateResponse& _internal_match_create_res() const;
  ::Internal::MatchCreateResponse* _internal_mutable_match_create_res();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:Internal.GamePacket)
 private:
  class _Internal;
  void set_has_match_create_req();
  void set_has_match_create_res();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 3, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GamePacket& from_msg);
    ::uint32_t sequence_id_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::Internal::MatchCreateRequest* match_create_req_;
      ::Internal::MatchCreateResponse* match_create_res_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Internal_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GamePacket

// uint32 sequence_id = 1;
inline void GamePacket::clear_sequence_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_id_ = 0u;
}
inline ::uint32_t GamePacket::sequence_id() const {
  // @@protoc_insertion_point(field_get:Internal.GamePacket.sequence_id)
  return _internal_sequence_id();
}
inline void GamePacket::set_sequence_id(::uint32_t value) {
  _internal_set_sequence_id(value);
  // @@protoc_insertion_point(field_set:Internal.GamePacket.sequence_id)
}
inline ::uint32_t GamePacket::_internal_sequence_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequence_id_;
}
inline void GamePacket::_internal_set_sequence_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_id_ = value;
}

// .Internal.MatchCreateRequest match_create_req = 10;
inline bool GamePacket::has_match_create_req() const {
  return payload_case() == kMatchCreateReq;
}
inline bool GamePacket::_internal_has_match_create_req() const {
  return payload_case() == kMatchCreateReq;
}
inline void GamePacket::set_has_match_create_req() {
  _impl_._oneof_case_[0] = kMatchCreateReq;
}
inline void GamePacket::clear_match_create_req() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMatchCreateReq) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.match_create_req_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.match_create_req_);
    }
    clear_has_payload();
  }
}
inline ::Internal::MatchCreateRequest* GamePacket::release_match_create_req() {
  // @@protoc_insertion_point(field_release:Internal.GamePacket.match_create_req)
  if (payload_case() == kMatchCreateReq) {
    clear_has_payload();
    auto* temp = _impl_.payload_.match_create_req_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.match_create_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Internal::MatchCreateRequest& GamePacket::_internal_match_create_req() const {
  return payload_case() == kMatchCreateReq ? *_impl_.payload_.match_create_req_ : reinterpret_cast<::Internal::MatchCreateRequest&>(::Internal::_MatchCreateRequest_default_instance_);
}
inline const ::Internal::MatchCreateRequest& GamePacket::match_create_req() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.GamePacket.match_create_req)
  return _internal_match_create_req();
}
inline ::Internal::MatchCreateRequest* GamePacket::unsafe_arena_release_match_create_req() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Internal.GamePacket.match_create_req)
  if (payload_case() == kMatchCreateReq) {
    clear_has_payload();
    auto* temp = _impl_.payload_.match_create_req_;
    _impl_.payload_.match_create_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GamePacket::unsafe_arena_set_allocated_match_create_req(::Internal::MatchCreateRequest* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_match_create_req();
    _impl_.payload_.match_create_req_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Internal.GamePacket.match_create_req)
}
inline ::Internal::MatchCreateRequest* GamePacket::_internal_mutable_match_create_req() {
  if (payload_case() != kMatchCreateReq) {
    clear_payload();
    set_has_match_create_req();
    _impl_.payload_.match_create_req_ =
        ::google::protobuf::Message::DefaultConstruct<::Internal::MatchCreateRequest>(GetArena());
  }
  return _impl_.payload_.match_create_req_;
}
inline ::Internal::MatchCreateRequest* GamePacket::mutable_match_create_req() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Internal::MatchCreateRequest* _msg = _internal_mutable_match_create_req();
  // @@protoc_insertion_point(field_mutable:Internal.GamePacket.match_create_req)
  return _msg;
}

// .Internal.MatchCreateResponse match_create_res = 11;
inline bool GamePacket::has_match_create_res() const {
  return payload_case() == kMatchCreateRes;
}
inline bool GamePacket::_internal_has_match_create_res() const {
  return payload_case() == kMatchCreateRes;
}
inline void GamePacket::set_has_match_create_res() {
  _impl_._oneof_case_[0] = kMatchCreateRes;
}
inline void GamePacket::clear_match_create_res() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMatchCreateRes) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.match_create_res_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.match_create_res_);
    }
    clear_has_payload();
  }
}
inline ::Internal::MatchCreateResponse* GamePacket::release_match_create_res() {
  // @@protoc_insertion_point(field_release:Internal.GamePacket.match_create_res)
  if (payload_case() == kMatchCreateRes) {
    clear_has_payload();
    auto* temp = _impl_.payload_.match_create_res_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.match_create_res_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Internal::MatchCreateResponse& GamePacket::_internal_match_create_res() const {
  return payload_case() == kMatchCreateRes ? *_impl_.payload_.match_create_res_ : reinterpret_cast<::Internal::MatchCreateResponse&>(::Internal::_MatchCreateResponse_default_instance_);
}
inline const ::Internal::MatchCreateResponse& GamePacket::match_create_res() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.GamePacket.match_create_res)
  return _internal_match_create_res();
}
inline ::Internal::MatchCreateResponse* GamePacket::unsafe_arena_release_match_create_res() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Internal.GamePacket.match_create_res)
  if (payload_case() == kMatchCreateRes) {
    clear_has_payload();
    auto* temp = _impl_.payload_.match_create_res_;
    _impl_.payload_.match_create_res_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GamePacket::unsafe_arena_set_allocated_match_create_res(::Internal::MatchCreateResponse* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_match_create_res();
    _impl_.payload_.match_create_res_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Internal.GamePacket.match_create_res)
}
inline ::Internal::MatchCreateResponse* GamePacket::_internal_mutable_match_create_res() {
  if (payload_case() != kMatchCreateRes) {
    clear_payload();
    set_has_match_create_res();
    _impl_.payload_.match_create_res_ =
        ::google::protobuf::Message::DefaultConstruct<::Internal::MatchCreateResponse>(GetArena());
  }
  return _impl_.payload_.match_create_res_;
}
inline ::Internal::MatchCreateResponse* GamePacket::mutable_match_create_res() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Internal::MatchCreateResponse* _msg = _internal_mutable_match_create_res();
  // @@protoc_insertion_point(field_mutable:Internal.GamePacket.match_create_res)
  return _msg;
}

inline bool GamePacket::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void GamePacket::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline GamePacket::PayloadCase GamePacket::payload_case() const {
  return GamePacket::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// UserSessionInfo

// string user_id = 1;
inline void UserSessionInfo::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.ClearToEmpty();
}
inline const std::string& UserSessionInfo::user_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.UserSessionInfo.user_id)
  return _internal_user_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UserSessionInfo::set_user_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Internal.UserSessionInfo.user_id)
}
inline std::string* UserSessionInfo::mutable_user_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:Internal.UserSessionInfo.user_id)
  return _s;
}
inline const std::string& UserSessionInfo::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_.Get();
}
inline void UserSessionInfo::_internal_set_user_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.Set(value, GetArena());
}
inline std::string* UserSessionInfo::_internal_mutable_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.user_id_.Mutable( GetArena());
}
inline std::string* UserSessionInfo::release_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Internal.UserSessionInfo.user_id)
  return _impl_.user_id_.Release();
}
inline void UserSessionInfo::set_allocated_user_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Internal.UserSessionInfo.user_id)
}

// string session_token = 2;
inline void UserSessionInfo::clear_session_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_token_.ClearToEmpty();
}
inline const std::string& UserSessionInfo::session_token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.UserSessionInfo.session_token)
  return _internal_session_token();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UserSessionInfo::set_session_token(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Internal.UserSessionInfo.session_token)
}
inline std::string* UserSessionInfo::mutable_session_token() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_session_token();
  // @@protoc_insertion_point(field_mutable:Internal.UserSessionInfo.session_token)
  return _s;
}
inline const std::string& UserSessionInfo::_internal_session_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_token_.Get();
}
inline void UserSessionInfo::_internal_set_session_token(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_token_.Set(value, GetArena());
}
inline std::string* UserSessionInfo::_internal_mutable_session_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_token_.Mutable( GetArena());
}
inline std::string* UserSessionInfo::release_session_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Internal.UserSessionInfo.session_token)
  return _impl_.session_token_.Release();
}
inline void UserSessionInfo::set_allocated_session_token(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_token_.IsDefault()) {
    _impl_.session_token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Internal.UserSessionInfo.session_token)
}

// -------------------------------------------------------------------

// MatchCreateRequest

// string match_id = 1;
inline void MatchCreateRequest::clear_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.ClearToEmpty();
}
inline const std::string& MatchCreateRequest::match_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.MatchCreateRequest.match_id)
  return _internal_match_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MatchCreateRequest::set_match_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Internal.MatchCreateRequest.match_id)
}
inline std::string* MatchCreateRequest::mutable_match_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_match_id();
  // @@protoc_insertion_point(field_mutable:Internal.MatchCreateRequest.match_id)
  return _s;
}
inline const std::string& MatchCreateRequest::_internal_match_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.match_id_.Get();
}
inline void MatchCreateRequest::_internal_set_match_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.Set(value, GetArena());
}
inline std::string* MatchCreateRequest::_internal_mutable_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.match_id_.Mutable( GetArena());
}
inline std::string* MatchCreateRequest::release_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Internal.MatchCreateRequest.match_id)
  return _impl_.match_id_.Release();
}
inline void MatchCreateRequest::set_allocated_match_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.match_id_.IsDefault()) {
    _impl_.match_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Internal.MatchCreateRequest.match_id)
}

// string game_type = 2;
inline void MatchCreateRequest::clear_game_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_type_.ClearToEmpty();
}
inline const std::string& MatchCreateRequest::game_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.MatchCreateRequest.game_type)
  return _internal_game_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MatchCreateRequest::set_game_type(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Internal.MatchCreateRequest.game_type)
}
inline std::string* MatchCreateRequest::mutable_game_type() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_game_type();
  // @@protoc_insertion_point(field_mutable:Internal.MatchCreateRequest.game_type)
  return _s;
}
inline const std::string& MatchCreateRequest::_internal_game_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.game_type_.Get();
}
inline void MatchCreateRequest::_internal_set_game_type(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_type_.Set(value, GetArena());
}
inline std::string* MatchCreateRequest::_internal_mutable_game_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.game_type_.Mutable( GetArena());
}
inline std::string* MatchCreateRequest::release_game_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Internal.MatchCreateRequest.game_type)
  return _impl_.game_type_.Release();
}
inline void MatchCreateRequest::set_allocated_game_type(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_type_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.game_type_.IsDefault()) {
    _impl_.game_type_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Internal.MatchCreateRequest.game_type)
}

// repeated .Internal.UserSessionInfo users = 3;
inline int MatchCreateRequest::_internal_users_size() const {
  return _internal_users().size();
}
inline int MatchCreateRequest::users_size() const {
  return _internal_users_size();
}
inline void MatchCreateRequest::clear_users() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.users_.Clear();
}
inline ::Internal::UserSessionInfo* MatchCreateRequest::mutable_users(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Internal.MatchCreateRequest.users)
  return _internal_mutable_users()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Internal::UserSessionInfo>* MatchCreateRequest::mutable_users()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Internal.MatchCreateRequest.users)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_users();
}
inline const ::Internal::UserSessionInfo& MatchCreateRequest::users(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.MatchCreateRequest.users)
  return _internal_users().Get(index);
}
inline ::Internal::UserSessionInfo* MatchCreateRequest::add_users() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Internal::UserSessionInfo* _add = _internal_mutable_users()->Add();
  // @@protoc_insertion_point(field_add:Internal.MatchCreateRequest.users)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Internal::UserSessionInfo>& MatchCreateRequest::users() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Internal.MatchCreateRequest.users)
  return _internal_users();
}
inline const ::google::protobuf::RepeatedPtrField<::Internal::UserSessionInfo>&
MatchCreateRequest::_internal_users() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.users_;
}
inline ::google::protobuf::RepeatedPtrField<::Internal::UserSessionInfo>*
MatchCreateRequest::_internal_mutable_users() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.users_;
}

// -------------------------------------------------------------------

// MatchCreateResponse

// string match_id = 1;
inline void MatchCreateResponse::clear_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.ClearToEmpty();
}
inline const std::string& MatchCreateResponse::match_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.MatchCreateResponse.match_id)
  return _internal_match_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MatchCreateResponse::set_match_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Internal.MatchCreateResponse.match_id)
}
inline std::string* MatchCreateResponse::mutable_match_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_match_id();
  // @@protoc_insertion_point(field_mutable:Internal.MatchCreateResponse.match_id)
  return _s;
}
inline const std::string& MatchCreateResponse::_internal_match_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.match_id_.Get();
}
inline void MatchCreateResponse::_internal_set_match_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.Set(value, GetArena());
}
inline std::string* MatchCreateResponse::_internal_mutable_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.match_id_.Mutable( GetArena());
}
inline std::string* MatchCreateResponse::release_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Internal.MatchCreateResponse.match_id)
  return _impl_.match_id_.Release();
}
inline void MatchCreateResponse::set_allocated_match_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.match_id_.IsDefault()) {
    _impl_.match_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Internal.MatchCreateResponse.match_id)
}

// bool success = 2;
inline void MatchCreateResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
}
inline bool MatchCreateResponse::success() const {
  // @@protoc_insertion_point(field_get:Internal.MatchCreateResponse.success)
  return _internal_success();
}
inline void MatchCreateResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Internal.MatchCreateResponse.success)
}
inline bool MatchCreateResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void MatchCreateResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// int32 port = 3;
inline void MatchCreateResponse::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0;
}
inline ::int32_t MatchCreateResponse::port() const {
  // @@protoc_insertion_point(field_get:Internal.MatchCreateResponse.port)
  return _internal_port();
}
inline void MatchCreateResponse::set_port(::int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:Internal.MatchCreateResponse.port)
}
inline ::int32_t MatchCreateResponse::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void MatchCreateResponse::_internal_set_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// string server_ip = 4;
inline void MatchCreateResponse::clear_server_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_ip_.ClearToEmpty();
}
inline const std::string& MatchCreateResponse::server_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.MatchCreateResponse.server_ip)
  return _internal_server_ip();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MatchCreateResponse::set_server_ip(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Internal.MatchCreateResponse.server_ip)
}
inline std::string* MatchCreateResponse::mutable_server_ip() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_server_ip();
  // @@protoc_insertion_point(field_mutable:Internal.MatchCreateResponse.server_ip)
  return _s;
}
inline const std::string& MatchCreateResponse::_internal_server_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_ip_.Get();
}
inline void MatchCreateResponse::_internal_set_server_ip(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_ip_.Set(value, GetArena());
}
inline std::string* MatchCreateResponse::_internal_mutable_server_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.server_ip_.Mutable( GetArena());
}
inline std::string* MatchCreateResponse::release_server_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Internal.MatchCreateResponse.server_ip)
  return _impl_.server_ip_.Release();
}
inline void MatchCreateResponse::set_allocated_server_ip(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.server_ip_.IsDefault()) {
    _impl_.server_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Internal.MatchCreateResponse.server_ip)
}

// string error_message = 5;
inline void MatchCreateResponse::clear_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& MatchCreateResponse::error_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Internal.MatchCreateResponse.error_message)
  return _internal_error_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MatchCreateResponse::set_error_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Internal.MatchCreateResponse.error_message)
}
inline std::string* MatchCreateResponse::mutable_error_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:Internal.MatchCreateResponse.error_message)
  return _s;
}
inline const std::string& MatchCreateResponse::_internal_error_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_message_.Get();
}
inline void MatchCreateResponse::_internal_set_error_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(value, GetArena());
}
inline std::string* MatchCreateResponse::_internal_mutable_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.error_message_.Mutable( GetArena());
}
inline std::string* MatchCreateResponse::release_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Internal.MatchCreateResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void MatchCreateResponse::set_allocated_error_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Internal.MatchCreateResponse.error_message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Internal


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Internal_2eproto_2epb_2eh
