// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Packet.proto
// Protobuf C++ Version: 6.33.4

#ifndef Packet_2eproto_2epb_2eh
#define Packet_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Packet_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Packet_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Packet_2eproto;
}  // extern "C"
namespace Protocol {
enum AuthenticationType : int;
extern const uint32_t AuthenticationType_internal_data_[];
enum IngameType : int;
extern const uint32_t IngameType_internal_data_[];
enum MatchmakingType : int;
extern const uint32_t MatchmakingType_internal_data_[];
enum PacketType : int;
extern const uint32_t PacketType_internal_data_[];
class AuthenticationPacket;
struct AuthenticationPacketDefaultTypeInternal;
extern AuthenticationPacketDefaultTypeInternal _AuthenticationPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AuthenticationPacket_class_data_;
class HitPacket;
struct HitPacketDefaultTypeInternal;
extern HitPacketDefaultTypeInternal _HitPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull HitPacket_class_data_;
class IngamePacket;
struct IngamePacketDefaultTypeInternal;
extern IngamePacketDefaultTypeInternal _IngamePacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull IngamePacket_class_data_;
class Matchmaking;
struct MatchmakingDefaultTypeInternal;
extern MatchmakingDefaultTypeInternal _Matchmaking_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Matchmaking_class_data_;
class Packet;
struct PacketDefaultTypeInternal;
extern PacketDefaultTypeInternal _Packet_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Packet_class_data_;
}  // namespace Protocol
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Protocol::AuthenticationType_internal_data_>
    internal::EnumTraitsImpl::value<::Protocol::AuthenticationType>;
template <>
internal::EnumTraitsT<::Protocol::IngameType_internal_data_>
    internal::EnumTraitsImpl::value<::Protocol::IngameType>;
template <>
internal::EnumTraitsT<::Protocol::MatchmakingType_internal_data_>
    internal::EnumTraitsImpl::value<::Protocol::MatchmakingType>;
template <>
internal::EnumTraitsT<::Protocol::PacketType_internal_data_>
    internal::EnumTraitsImpl::value<::Protocol::PacketType>;
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum PacketType : int {
  PacketOk = 0,
  InvalidData = 1,
  ErrorOccured = 2,
  PortHandshake = 100,
  InfoHandshake = 101,
  Ping = 102,
  Match = 103,
  Ingame = 200,
  Authentication = 201,
  PacketType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PacketType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PacketType_internal_data_[];
inline constexpr PacketType PacketType_MIN =
    static_cast<PacketType>(0);
inline constexpr PacketType PacketType_MAX =
    static_cast<PacketType>(201);
inline bool PacketType_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, PacketType_internal_data_);
}
inline constexpr int PacketType_ARRAYSIZE = 201 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PacketType_descriptor();
template <typename T>
const ::std::string& PacketType_Name(T value) {
  static_assert(::std::is_same<T, PacketType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PacketType_Name().");
  return ::google::protobuf::internal::NameOfEnum(PacketType_descriptor(), value);
}
inline bool PacketType_Parse(
    ::absl::string_view name, PacketType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PacketType>(PacketType_descriptor(), name,
                                           value);
}
enum IngameType : int {
  IngameOk = 0,
  Move = 1,
  Jump = 2,
  Shoot = 3,
  Hit = 4,
  IngameType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  IngameType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t IngameType_internal_data_[];
inline constexpr IngameType IngameType_MIN =
    static_cast<IngameType>(0);
inline constexpr IngameType IngameType_MAX =
    static_cast<IngameType>(4);
inline bool IngameType_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int IngameType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL IngameType_descriptor();
template <typename T>
const ::std::string& IngameType_Name(T value) {
  static_assert(::std::is_same<T, IngameType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to IngameType_Name().");
  return IngameType_Name(static_cast<IngameType>(value));
}
template <>
inline const ::std::string& IngameType_Name(IngameType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<IngameType_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool IngameType_Parse(
    ::absl::string_view name, IngameType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<IngameType>(IngameType_descriptor(), name,
                                           value);
}
enum MatchmakingType : int {
  MatchmakingOk = 0,
  Request = 1,
  Success = 2,
  Failed = 3,
  Waiting = 4,
  Matched = 5,
  MatchmakingType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  MatchmakingType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t MatchmakingType_internal_data_[];
inline constexpr MatchmakingType MatchmakingType_MIN =
    static_cast<MatchmakingType>(0);
inline constexpr MatchmakingType MatchmakingType_MAX =
    static_cast<MatchmakingType>(5);
inline bool MatchmakingType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int MatchmakingType_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MatchmakingType_descriptor();
template <typename T>
const ::std::string& MatchmakingType_Name(T value) {
  static_assert(::std::is_same<T, MatchmakingType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to MatchmakingType_Name().");
  return MatchmakingType_Name(static_cast<MatchmakingType>(value));
}
template <>
inline const ::std::string& MatchmakingType_Name(MatchmakingType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MatchmakingType_descriptor, 0, 5>(
      static_cast<int>(value));
}
inline bool MatchmakingType_Parse(
    ::absl::string_view name, MatchmakingType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<MatchmakingType>(MatchmakingType_descriptor(), name,
                                           value);
}
enum AuthenticationType : int {
  AuthenticationOk = 0,
  UdpHolePunching = 1,
  AuthenticationType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  AuthenticationType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t AuthenticationType_internal_data_[];
inline constexpr AuthenticationType AuthenticationType_MIN =
    static_cast<AuthenticationType>(0);
inline constexpr AuthenticationType AuthenticationType_MAX =
    static_cast<AuthenticationType>(1);
inline bool AuthenticationType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int AuthenticationType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AuthenticationType_descriptor();
template <typename T>
const ::std::string& AuthenticationType_Name(T value) {
  static_assert(::std::is_same<T, AuthenticationType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to AuthenticationType_Name().");
  return AuthenticationType_Name(static_cast<AuthenticationType>(value));
}
template <>
inline const ::std::string& AuthenticationType_Name(AuthenticationType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AuthenticationType_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool AuthenticationType_Parse(
    ::absl::string_view name, AuthenticationType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<AuthenticationType>(AuthenticationType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Packet final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.Packet) */ {
 public:
  inline Packet() : Packet(nullptr) {}
  ~Packet() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Packet* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Packet));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Packet(::google::protobuf::internal::ConstantInitialized);

  inline Packet(const Packet& from) : Packet(nullptr, from) {}
  inline Packet(Packet&& from) noexcept
      : Packet(nullptr, ::std::move(from)) {}
  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }
  inline Packet& operator=(Packet&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Packet& default_instance() {
    return *reinterpret_cast<const Packet*>(
        &_Packet_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Packet& a, Packet& b) { a.Swap(&b); }
  inline void Swap(Packet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Packet* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Packet* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Packet>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Packet& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Packet& from) { Packet::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Packet* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.Packet"; }

  explicit Packet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Packet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Packet& from);
  Packet(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Packet&& from) noexcept
      : Packet(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // bytes data = 2;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // .Protocol.PacketType type = 1;
  void clear_type() ;
  ::Protocol::PacketType type() const;
  void set_type(::Protocol::PacketType value);

  private:
  ::Protocol::PacketType _internal_type() const;
  void _internal_set_type(::Protocol::PacketType value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.Packet)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Packet& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Packet_class_data_;
// -------------------------------------------------------------------

class Matchmaking final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.Matchmaking) */ {
 public:
  inline Matchmaking() : Matchmaking(nullptr) {}
  ~Matchmaking() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Matchmaking* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Matchmaking));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Matchmaking(::google::protobuf::internal::ConstantInitialized);

  inline Matchmaking(const Matchmaking& from) : Matchmaking(nullptr, from) {}
  inline Matchmaking(Matchmaking&& from) noexcept
      : Matchmaking(nullptr, ::std::move(from)) {}
  inline Matchmaking& operator=(const Matchmaking& from) {
    CopyFrom(from);
    return *this;
  }
  inline Matchmaking& operator=(Matchmaking&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Matchmaking& default_instance() {
    return *reinterpret_cast<const Matchmaking*>(
        &_Matchmaking_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Matchmaking& a, Matchmaking& b) { a.Swap(&b); }
  inline void Swap(Matchmaking* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Matchmaking* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Matchmaking* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Matchmaking>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Matchmaking& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Matchmaking& from) { Matchmaking::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Matchmaking* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.Matchmaking"; }

  explicit Matchmaking(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Matchmaking(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Matchmaking& from);
  Matchmaking(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Matchmaking&& from) noexcept
      : Matchmaking(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 2,
    kRoomIdFieldNumber = 3,
    kTypeFieldNumber = 1,
  };
  // bytes sessionId = 2;
  void clear_sessionid() ;
  const ::std::string& sessionid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_sessionid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_sessionid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_sessionid();
  void set_allocated_sessionid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_sessionid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sessionid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_sessionid();

  public:
  // optional bytes roomId = 3;
  bool has_roomid() const;
  void clear_roomid() ;
  const ::std::string& roomid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_roomid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_roomid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_roomid();
  void set_allocated_roomid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_roomid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_roomid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_roomid();

  public:
  // .Protocol.MatchmakingType type = 1;
  void clear_type() ;
  ::Protocol::MatchmakingType type() const;
  void set_type(::Protocol::MatchmakingType value);

  private:
  ::Protocol::MatchmakingType _internal_type() const;
  void _internal_set_type(::Protocol::MatchmakingType value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.Matchmaking)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Matchmaking& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sessionid_;
    ::google::protobuf::internal::ArenaStringPtr roomid_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Matchmaking_class_data_;
// -------------------------------------------------------------------

class IngamePacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.IngamePacket) */ {
 public:
  inline IngamePacket() : IngamePacket(nullptr) {}
  ~IngamePacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IngamePacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IngamePacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR IngamePacket(::google::protobuf::internal::ConstantInitialized);

  inline IngamePacket(const IngamePacket& from) : IngamePacket(nullptr, from) {}
  inline IngamePacket(IngamePacket&& from) noexcept
      : IngamePacket(nullptr, ::std::move(from)) {}
  inline IngamePacket& operator=(const IngamePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline IngamePacket& operator=(IngamePacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IngamePacket& default_instance() {
    return *reinterpret_cast<const IngamePacket*>(
        &_IngamePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(IngamePacket& a, IngamePacket& b) { a.Swap(&b); }
  inline void Swap(IngamePacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IngamePacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IngamePacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IngamePacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IngamePacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IngamePacket& from) { IngamePacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IngamePacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.IngamePacket"; }

  explicit IngamePacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  IngamePacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const IngamePacket& from);
  IngamePacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, IngamePacket&& from) noexcept
      : IngamePacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 1,
    kRoomIdFieldNumber = 2,
    kDataFieldNumber = 4,
    kClientTickFieldNumber = 5,
    kMethodFieldNumber = 3,
  };
  // bytes sessionId = 1;
  void clear_sessionid() ;
  const ::std::string& sessionid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_sessionid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_sessionid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_sessionid();
  void set_allocated_sessionid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_sessionid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sessionid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_sessionid();

  public:
  // bytes roomId = 2;
  void clear_roomid() ;
  const ::std::string& roomid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_roomid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_roomid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_roomid();
  void set_allocated_roomid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_roomid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_roomid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_roomid();

  public:
  // bytes data = 4;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // uint64 clientTick = 5;
  void clear_clienttick() ;
  ::uint64_t clienttick() const;
  void set_clienttick(::uint64_t value);

  private:
  ::uint64_t _internal_clienttick() const;
  void _internal_set_clienttick(::uint64_t value);

  public:
  // .Protocol.IngameType method = 3;
  void clear_method() ;
  ::Protocol::IngameType method() const;
  void set_method(::Protocol::IngameType value);

  private:
  ::Protocol::IngameType _internal_method() const;
  void _internal_set_method(::Protocol::IngameType value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.IngamePacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const IngamePacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sessionid_;
    ::google::protobuf::internal::ArenaStringPtr roomid_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::uint64_t clienttick_;
    int method_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull IngamePacket_class_data_;
// -------------------------------------------------------------------

class HitPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.HitPacket) */ {
 public:
  inline HitPacket() : HitPacket(nullptr) {}
  ~HitPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HitPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HitPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HitPacket(::google::protobuf::internal::ConstantInitialized);

  inline HitPacket(const HitPacket& from) : HitPacket(nullptr, from) {}
  inline HitPacket(HitPacket&& from) noexcept
      : HitPacket(nullptr, ::std::move(from)) {}
  inline HitPacket& operator=(const HitPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline HitPacket& operator=(HitPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HitPacket& default_instance() {
    return *reinterpret_cast<const HitPacket*>(
        &_HitPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(HitPacket& a, HitPacket& b) { a.Swap(&b); }
  inline void Swap(HitPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HitPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HitPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HitPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HitPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HitPacket& from) { HitPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HitPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.HitPacket"; }

  explicit HitPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HitPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HitPacket& from);
  HitPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HitPacket&& from) noexcept
      : HitPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHitPlayerIdFieldNumber = 1,
    kShooterIdFieldNumber = 2,
    kCurrentHpFieldNumber = 3,
    kDeathsFieldNumber = 4,
    kIsDeadFieldNumber = 5,
    kDamageFieldNumber = 6,
  };
  // bytes hitPlayerId = 1;
  void clear_hitplayerid() ;
  const ::std::string& hitplayerid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_hitplayerid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_hitplayerid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_hitplayerid();
  void set_allocated_hitplayerid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_hitplayerid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_hitplayerid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_hitplayerid();

  public:
  // bytes shooterId = 2;
  void clear_shooterid() ;
  const ::std::string& shooterid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_shooterid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_shooterid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_shooterid();
  void set_allocated_shooterid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_shooterid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_shooterid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_shooterid();

  public:
  // int32 currentHp = 3;
  void clear_currenthp() ;
  ::int32_t currenthp() const;
  void set_currenthp(::int32_t value);

  private:
  ::int32_t _internal_currenthp() const;
  void _internal_set_currenthp(::int32_t value);

  public:
  // int32 deaths = 4;
  void clear_deaths() ;
  ::int32_t deaths() const;
  void set_deaths(::int32_t value);

  private:
  ::int32_t _internal_deaths() const;
  void _internal_set_deaths(::int32_t value);

  public:
  // bool isDead = 5;
  void clear_isdead() ;
  bool isdead() const;
  void set_isdead(bool value);

  private:
  bool _internal_isdead() const;
  void _internal_set_isdead(bool value);

  public:
  // int32 damage = 6;
  void clear_damage() ;
  ::int32_t damage() const;
  void set_damage(::int32_t value);

  private:
  ::int32_t _internal_damage() const;
  void _internal_set_damage(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.HitPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HitPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr hitplayerid_;
    ::google::protobuf::internal::ArenaStringPtr shooterid_;
    ::int32_t currenthp_;
    ::int32_t deaths_;
    bool isdead_;
    ::int32_t damage_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HitPacket_class_data_;
// -------------------------------------------------------------------

class AuthenticationPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.AuthenticationPacket) */ {
 public:
  inline AuthenticationPacket() : AuthenticationPacket(nullptr) {}
  ~AuthenticationPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AuthenticationPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AuthenticationPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AuthenticationPacket(::google::protobuf::internal::ConstantInitialized);

  inline AuthenticationPacket(const AuthenticationPacket& from) : AuthenticationPacket(nullptr, from) {}
  inline AuthenticationPacket(AuthenticationPacket&& from) noexcept
      : AuthenticationPacket(nullptr, ::std::move(from)) {}
  inline AuthenticationPacket& operator=(const AuthenticationPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthenticationPacket& operator=(AuthenticationPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthenticationPacket& default_instance() {
    return *reinterpret_cast<const AuthenticationPacket*>(
        &_AuthenticationPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(AuthenticationPacket& a, AuthenticationPacket& b) { a.Swap(&b); }
  inline void Swap(AuthenticationPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthenticationPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthenticationPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AuthenticationPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AuthenticationPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AuthenticationPacket& from) { AuthenticationPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AuthenticationPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.AuthenticationPacket"; }

  explicit AuthenticationPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AuthenticationPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AuthenticationPacket& from);
  AuthenticationPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AuthenticationPacket&& from) noexcept
      : AuthenticationPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 1,
    kRoomIdFieldNumber = 2,
    kDataFieldNumber = 4,
    kMethodFieldNumber = 3,
  };
  // bytes sessionId = 1;
  void clear_sessionid() ;
  const ::std::string& sessionid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_sessionid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_sessionid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_sessionid();
  void set_allocated_sessionid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_sessionid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sessionid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_sessionid();

  public:
  // bytes roomId = 2;
  void clear_roomid() ;
  const ::std::string& roomid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_roomid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_roomid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_roomid();
  void set_allocated_roomid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_roomid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_roomid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_roomid();

  public:
  // bytes data = 4;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // .Protocol.AuthenticationType method = 3;
  void clear_method() ;
  ::Protocol::AuthenticationType method() const;
  void set_method(::Protocol::AuthenticationType value);

  private:
  ::Protocol::AuthenticationType _internal_method() const;
  void _internal_set_method(::Protocol::AuthenticationType value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.AuthenticationPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AuthenticationPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sessionid_;
    ::google::protobuf::internal::ArenaStringPtr roomid_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    int method_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AuthenticationPacket_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Packet

// .Protocol.PacketType type = 1;
inline void Packet::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::Protocol::PacketType Packet::type() const {
  // @@protoc_insertion_point(field_get:Protocol.Packet.type)
  return _internal_type();
}
inline void Packet::set_type(::Protocol::PacketType value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Protocol.Packet.type)
}
inline ::Protocol::PacketType Packet::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::PacketType>(_impl_.type_);
}
inline void Packet::_internal_set_type(::Protocol::PacketType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// bytes data = 2;
inline void Packet::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Packet::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.Packet.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Packet::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.Packet.data)
}
inline ::std::string* PROTOBUF_NONNULL Packet::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Protocol.Packet.data)
  return _s;
}
inline const ::std::string& Packet::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void Packet::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Packet::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Packet::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.Packet.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void Packet::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.Packet.data)
}

// -------------------------------------------------------------------

// Matchmaking

// .Protocol.MatchmakingType type = 1;
inline void Matchmaking::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::Protocol::MatchmakingType Matchmaking::type() const {
  // @@protoc_insertion_point(field_get:Protocol.Matchmaking.type)
  return _internal_type();
}
inline void Matchmaking::set_type(::Protocol::MatchmakingType value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.Matchmaking.type)
}
inline ::Protocol::MatchmakingType Matchmaking::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::MatchmakingType>(_impl_.type_);
}
inline void Matchmaking::_internal_set_type(::Protocol::MatchmakingType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// bytes sessionId = 2;
inline void Matchmaking::clear_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Matchmaking::sessionid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.Matchmaking.sessionId)
  return _internal_sessionid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Matchmaking::set_sessionid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sessionid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.Matchmaking.sessionId)
}
inline ::std::string* PROTOBUF_NONNULL Matchmaking::mutable_sessionid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_sessionid();
  // @@protoc_insertion_point(field_mutable:Protocol.Matchmaking.sessionId)
  return _s;
}
inline const ::std::string& Matchmaking::_internal_sessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sessionid_.Get();
}
inline void Matchmaking::_internal_set_sessionid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Matchmaking::_internal_mutable_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sessionid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Matchmaking::release_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.Matchmaking.sessionId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.sessionid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sessionid_.Set("", GetArena());
  }
  return released;
}
inline void Matchmaking::set_allocated_sessionid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.sessionid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sessionid_.IsDefault()) {
    _impl_.sessionid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.Matchmaking.sessionId)
}

// optional bytes roomId = 3;
inline bool Matchmaking::has_roomid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Matchmaking::clear_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Matchmaking::roomid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.Matchmaking.roomId)
  return _internal_roomid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Matchmaking::set_roomid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.roomid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.Matchmaking.roomId)
}
inline ::std::string* PROTOBUF_NONNULL Matchmaking::mutable_roomid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_roomid();
  // @@protoc_insertion_point(field_mutable:Protocol.Matchmaking.roomId)
  return _s;
}
inline const ::std::string& Matchmaking::_internal_roomid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomid_.Get();
}
inline void Matchmaking::_internal_set_roomid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Matchmaking::_internal_mutable_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.roomid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Matchmaking::release_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.Matchmaking.roomId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.roomid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.roomid_.Set("", GetArena());
  }
  return released;
}
inline void Matchmaking::set_allocated_roomid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.roomid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.roomid_.IsDefault()) {
    _impl_.roomid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.Matchmaking.roomId)
}

// -------------------------------------------------------------------

// IngamePacket

// bytes sessionId = 1;
inline void IngamePacket::clear_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& IngamePacket::sessionid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.IngamePacket.sessionId)
  return _internal_sessionid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void IngamePacket::set_sessionid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sessionid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.IngamePacket.sessionId)
}
inline ::std::string* PROTOBUF_NONNULL IngamePacket::mutable_sessionid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_sessionid();
  // @@protoc_insertion_point(field_mutable:Protocol.IngamePacket.sessionId)
  return _s;
}
inline const ::std::string& IngamePacket::_internal_sessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sessionid_.Get();
}
inline void IngamePacket::_internal_set_sessionid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL IngamePacket::_internal_mutable_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sessionid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE IngamePacket::release_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.IngamePacket.sessionId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.sessionid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sessionid_.Set("", GetArena());
  }
  return released;
}
inline void IngamePacket::set_allocated_sessionid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.sessionid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sessionid_.IsDefault()) {
    _impl_.sessionid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.IngamePacket.sessionId)
}

// bytes roomId = 2;
inline void IngamePacket::clear_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& IngamePacket::roomid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.IngamePacket.roomId)
  return _internal_roomid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void IngamePacket::set_roomid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.roomid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.IngamePacket.roomId)
}
inline ::std::string* PROTOBUF_NONNULL IngamePacket::mutable_roomid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_roomid();
  // @@protoc_insertion_point(field_mutable:Protocol.IngamePacket.roomId)
  return _s;
}
inline const ::std::string& IngamePacket::_internal_roomid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomid_.Get();
}
inline void IngamePacket::_internal_set_roomid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL IngamePacket::_internal_mutable_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.roomid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE IngamePacket::release_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.IngamePacket.roomId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.roomid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.roomid_.Set("", GetArena());
  }
  return released;
}
inline void IngamePacket::set_allocated_roomid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.roomid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.roomid_.IsDefault()) {
    _impl_.roomid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.IngamePacket.roomId)
}

// .Protocol.IngameType method = 3;
inline void IngamePacket::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::Protocol::IngameType IngamePacket::method() const {
  // @@protoc_insertion_point(field_get:Protocol.IngamePacket.method)
  return _internal_method();
}
inline void IngamePacket::set_method(::Protocol::IngameType value) {
  _internal_set_method(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:Protocol.IngamePacket.method)
}
inline ::Protocol::IngameType IngamePacket::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::IngameType>(_impl_.method_);
}
inline void IngamePacket::_internal_set_method(::Protocol::IngameType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = value;
}

// bytes data = 4;
inline void IngamePacket::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& IngamePacket::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.IngamePacket.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void IngamePacket::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.IngamePacket.data)
}
inline ::std::string* PROTOBUF_NONNULL IngamePacket::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Protocol.IngamePacket.data)
  return _s;
}
inline const ::std::string& IngamePacket::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void IngamePacket::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL IngamePacket::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE IngamePacket::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.IngamePacket.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void IngamePacket::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.IngamePacket.data)
}

// uint64 clientTick = 5;
inline void IngamePacket::clear_clienttick() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clienttick_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t IngamePacket::clienttick() const {
  // @@protoc_insertion_point(field_get:Protocol.IngamePacket.clientTick)
  return _internal_clienttick();
}
inline void IngamePacket::set_clienttick(::uint64_t value) {
  _internal_set_clienttick(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:Protocol.IngamePacket.clientTick)
}
inline ::uint64_t IngamePacket::_internal_clienttick() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clienttick_;
}
inline void IngamePacket::_internal_set_clienttick(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clienttick_ = value;
}

// -------------------------------------------------------------------

// AuthenticationPacket

// bytes sessionId = 1;
inline void AuthenticationPacket::clear_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& AuthenticationPacket::sessionid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.AuthenticationPacket.sessionId)
  return _internal_sessionid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AuthenticationPacket::set_sessionid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sessionid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.AuthenticationPacket.sessionId)
}
inline ::std::string* PROTOBUF_NONNULL AuthenticationPacket::mutable_sessionid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_sessionid();
  // @@protoc_insertion_point(field_mutable:Protocol.AuthenticationPacket.sessionId)
  return _s;
}
inline const ::std::string& AuthenticationPacket::_internal_sessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sessionid_.Get();
}
inline void AuthenticationPacket::_internal_set_sessionid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AuthenticationPacket::_internal_mutable_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sessionid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AuthenticationPacket::release_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.AuthenticationPacket.sessionId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.sessionid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sessionid_.Set("", GetArena());
  }
  return released;
}
inline void AuthenticationPacket::set_allocated_sessionid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.sessionid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sessionid_.IsDefault()) {
    _impl_.sessionid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.AuthenticationPacket.sessionId)
}

// bytes roomId = 2;
inline void AuthenticationPacket::clear_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& AuthenticationPacket::roomid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.AuthenticationPacket.roomId)
  return _internal_roomid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AuthenticationPacket::set_roomid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.roomid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.AuthenticationPacket.roomId)
}
inline ::std::string* PROTOBUF_NONNULL AuthenticationPacket::mutable_roomid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_roomid();
  // @@protoc_insertion_point(field_mutable:Protocol.AuthenticationPacket.roomId)
  return _s;
}
inline const ::std::string& AuthenticationPacket::_internal_roomid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomid_.Get();
}
inline void AuthenticationPacket::_internal_set_roomid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AuthenticationPacket::_internal_mutable_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.roomid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AuthenticationPacket::release_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.AuthenticationPacket.roomId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.roomid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.roomid_.Set("", GetArena());
  }
  return released;
}
inline void AuthenticationPacket::set_allocated_roomid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.roomid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.roomid_.IsDefault()) {
    _impl_.roomid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.AuthenticationPacket.roomId)
}

// .Protocol.AuthenticationType method = 3;
inline void AuthenticationPacket::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::Protocol::AuthenticationType AuthenticationPacket::method() const {
  // @@protoc_insertion_point(field_get:Protocol.AuthenticationPacket.method)
  return _internal_method();
}
inline void AuthenticationPacket::set_method(::Protocol::AuthenticationType value) {
  _internal_set_method(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:Protocol.AuthenticationPacket.method)
}
inline ::Protocol::AuthenticationType AuthenticationPacket::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::AuthenticationType>(_impl_.method_);
}
inline void AuthenticationPacket::_internal_set_method(::Protocol::AuthenticationType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = value;
}

// bytes data = 4;
inline void AuthenticationPacket::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& AuthenticationPacket::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.AuthenticationPacket.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AuthenticationPacket::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.AuthenticationPacket.data)
}
inline ::std::string* PROTOBUF_NONNULL AuthenticationPacket::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Protocol.AuthenticationPacket.data)
  return _s;
}
inline const ::std::string& AuthenticationPacket::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void AuthenticationPacket::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AuthenticationPacket::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AuthenticationPacket::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.AuthenticationPacket.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void AuthenticationPacket::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.AuthenticationPacket.data)
}

// -------------------------------------------------------------------

// HitPacket

// bytes hitPlayerId = 1;
inline void HitPacket::clear_hitplayerid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hitplayerid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& HitPacket::hitplayerid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.HitPacket.hitPlayerId)
  return _internal_hitplayerid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HitPacket::set_hitplayerid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.hitplayerid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.HitPacket.hitPlayerId)
}
inline ::std::string* PROTOBUF_NONNULL HitPacket::mutable_hitplayerid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_hitplayerid();
  // @@protoc_insertion_point(field_mutable:Protocol.HitPacket.hitPlayerId)
  return _s;
}
inline const ::std::string& HitPacket::_internal_hitplayerid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hitplayerid_.Get();
}
inline void HitPacket::_internal_set_hitplayerid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hitplayerid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HitPacket::_internal_mutable_hitplayerid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.hitplayerid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HitPacket::release_hitplayerid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.HitPacket.hitPlayerId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.hitplayerid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.hitplayerid_.Set("", GetArena());
  }
  return released;
}
inline void HitPacket::set_allocated_hitplayerid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.hitplayerid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hitplayerid_.IsDefault()) {
    _impl_.hitplayerid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.HitPacket.hitPlayerId)
}

// bytes shooterId = 2;
inline void HitPacket::clear_shooterid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shooterid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& HitPacket::shooterid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.HitPacket.shooterId)
  return _internal_shooterid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HitPacket::set_shooterid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.shooterid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.HitPacket.shooterId)
}
inline ::std::string* PROTOBUF_NONNULL HitPacket::mutable_shooterid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_shooterid();
  // @@protoc_insertion_point(field_mutable:Protocol.HitPacket.shooterId)
  return _s;
}
inline const ::std::string& HitPacket::_internal_shooterid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.shooterid_.Get();
}
inline void HitPacket::_internal_set_shooterid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shooterid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HitPacket::_internal_mutable_shooterid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.shooterid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HitPacket::release_shooterid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.HitPacket.shooterId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.shooterid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.shooterid_.Set("", GetArena());
  }
  return released;
}
inline void HitPacket::set_allocated_shooterid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.shooterid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.shooterid_.IsDefault()) {
    _impl_.shooterid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.HitPacket.shooterId)
}

// int32 currentHp = 3;
inline void HitPacket::clear_currenthp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currenthp_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t HitPacket::currenthp() const {
  // @@protoc_insertion_point(field_get:Protocol.HitPacket.currentHp)
  return _internal_currenthp();
}
inline void HitPacket::set_currenthp(::int32_t value) {
  _internal_set_currenthp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.HitPacket.currentHp)
}
inline ::int32_t HitPacket::_internal_currenthp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.currenthp_;
}
inline void HitPacket::_internal_set_currenthp(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currenthp_ = value;
}

// int32 deaths = 4;
inline void HitPacket::clear_deaths() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.deaths_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t HitPacket::deaths() const {
  // @@protoc_insertion_point(field_get:Protocol.HitPacket.deaths)
  return _internal_deaths();
}
inline void HitPacket::set_deaths(::int32_t value) {
  _internal_set_deaths(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:Protocol.HitPacket.deaths)
}
inline ::int32_t HitPacket::_internal_deaths() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.deaths_;
}
inline void HitPacket::_internal_set_deaths(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.deaths_ = value;
}

// bool isDead = 5;
inline void HitPacket::clear_isdead() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isdead_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline bool HitPacket::isdead() const {
  // @@protoc_insertion_point(field_get:Protocol.HitPacket.isDead)
  return _internal_isdead();
}
inline void HitPacket::set_isdead(bool value) {
  _internal_set_isdead(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:Protocol.HitPacket.isDead)
}
inline bool HitPacket::_internal_isdead() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isdead_;
}
inline void HitPacket::_internal_set_isdead(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isdead_ = value;
}

// int32 damage = 6;
inline void HitPacket::clear_damage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.damage_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t HitPacket::damage() const {
  // @@protoc_insertion_point(field_get:Protocol.HitPacket.damage)
  return _internal_damage();
}
inline void HitPacket::set_damage(::int32_t value) {
  _internal_set_damage(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:Protocol.HitPacket.damage)
}
inline ::int32_t HitPacket::_internal_damage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.damage_;
}
inline void HitPacket::_internal_set_damage(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.damage_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::PacketType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Protocol::PacketType>() {
  return ::Protocol::PacketType_descriptor();
}
template <>
struct is_proto_enum<::Protocol::IngameType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Protocol::IngameType>() {
  return ::Protocol::IngameType_descriptor();
}
template <>
struct is_proto_enum<::Protocol::MatchmakingType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Protocol::MatchmakingType>() {
  return ::Protocol::MatchmakingType_descriptor();
}
template <>
struct is_proto_enum<::Protocol::AuthenticationType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Protocol::AuthenticationType>() {
  return ::Protocol::AuthenticationType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Packet_2eproto_2epb_2eh
