// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Packet.proto
// Protobuf C++ Version: 5.29.5

#ifndef Packet_2eproto_2epb_2eh
#define Packet_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Packet_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Packet_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Packet_2eproto;
namespace Protocol {
class AuthenticationPacket;
struct AuthenticationPacketDefaultTypeInternal;
extern AuthenticationPacketDefaultTypeInternal _AuthenticationPacket_default_instance_;
class IngamePacket;
struct IngamePacketDefaultTypeInternal;
extern IngamePacketDefaultTypeInternal _IngamePacket_default_instance_;
class Packet;
struct PacketDefaultTypeInternal;
extern PacketDefaultTypeInternal _Packet_default_instance_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum PacketType : int {
  Ok = 0,
  InvalidData = 1,
  ErrorOccured = 2,
  PortHandshake = 100,
  InfoHandshake = 101,
  Ping = 102,
  Ingame = 200,
  Autentication = 201,
  PacketType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PacketType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PacketType_IsValid(int value);
extern const uint32_t PacketType_internal_data_[];
constexpr PacketType PacketType_MIN = static_cast<PacketType>(0);
constexpr PacketType PacketType_MAX = static_cast<PacketType>(201);
constexpr int PacketType_ARRAYSIZE = 201 + 1;
const ::google::protobuf::EnumDescriptor*
PacketType_descriptor();
template <typename T>
const std::string& PacketType_Name(T value) {
  static_assert(std::is_same<T, PacketType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PacketType_Name().");
  return ::google::protobuf::internal::NameOfEnum(PacketType_descriptor(), value);
}
inline bool PacketType_Parse(absl::string_view name, PacketType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PacketType>(
      PacketType_descriptor(), name, value);
}
enum IngameType : int {
  IngameOk = 0,
  Move = 1,
  Jump = 2,
  Shoot = 3,
  Hit = 4,
  IngameType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  IngameType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool IngameType_IsValid(int value);
extern const uint32_t IngameType_internal_data_[];
constexpr IngameType IngameType_MIN = static_cast<IngameType>(0);
constexpr IngameType IngameType_MAX = static_cast<IngameType>(4);
constexpr int IngameType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
IngameType_descriptor();
template <typename T>
const std::string& IngameType_Name(T value) {
  static_assert(std::is_same<T, IngameType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to IngameType_Name().");
  return IngameType_Name(static_cast<IngameType>(value));
}
template <>
inline const std::string& IngameType_Name(IngameType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<IngameType_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool IngameType_Parse(absl::string_view name, IngameType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<IngameType>(
      IngameType_descriptor(), name, value);
}
enum AuthenticationType : int {
  AuthenticationOk = 0,
  UdpHolePunching = 1,
  AuthenticationType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  AuthenticationType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool AuthenticationType_IsValid(int value);
extern const uint32_t AuthenticationType_internal_data_[];
constexpr AuthenticationType AuthenticationType_MIN = static_cast<AuthenticationType>(0);
constexpr AuthenticationType AuthenticationType_MAX = static_cast<AuthenticationType>(1);
constexpr int AuthenticationType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
AuthenticationType_descriptor();
template <typename T>
const std::string& AuthenticationType_Name(T value) {
  static_assert(std::is_same<T, AuthenticationType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to AuthenticationType_Name().");
  return AuthenticationType_Name(static_cast<AuthenticationType>(value));
}
template <>
inline const std::string& AuthenticationType_Name(AuthenticationType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AuthenticationType_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool AuthenticationType_Parse(absl::string_view name, AuthenticationType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AuthenticationType>(
      AuthenticationType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Packet final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.Packet) */ {
 public:
  inline Packet() : Packet(nullptr) {}
  ~Packet() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Packet* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Packet));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Packet(
      ::google::protobuf::internal::ConstantInitialized);

  inline Packet(const Packet& from) : Packet(nullptr, from) {}
  inline Packet(Packet&& from) noexcept
      : Packet(nullptr, std::move(from)) {}
  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }
  inline Packet& operator=(Packet&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Packet& default_instance() {
    return *internal_default_instance();
  }
  static inline const Packet* internal_default_instance() {
    return reinterpret_cast<const Packet*>(
        &_Packet_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Packet& a, Packet& b) { a.Swap(&b); }
  inline void Swap(Packet* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Packet* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Packet* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Packet>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Packet& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Packet& from) { Packet::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Packet* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.Packet"; }

 protected:
  explicit Packet(::google::protobuf::Arena* arena);
  Packet(::google::protobuf::Arena* arena, const Packet& from);
  Packet(::google::protobuf::Arena* arena, Packet&& from) noexcept
      : Packet(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // bytes data = 2;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // .Protocol.PacketType type = 1;
  void clear_type() ;
  ::Protocol::PacketType type() const;
  void set_type(::Protocol::PacketType value);

  private:
  ::Protocol::PacketType _internal_type() const;
  void _internal_set_type(::Protocol::PacketType value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.Packet)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Packet& from_msg);
    ::google::protobuf::internal::ArenaStringPtr data_;
    int type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class IngamePacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.IngamePacket) */ {
 public:
  inline IngamePacket() : IngamePacket(nullptr) {}
  ~IngamePacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IngamePacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IngamePacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR IngamePacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline IngamePacket(const IngamePacket& from) : IngamePacket(nullptr, from) {}
  inline IngamePacket(IngamePacket&& from) noexcept
      : IngamePacket(nullptr, std::move(from)) {}
  inline IngamePacket& operator=(const IngamePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline IngamePacket& operator=(IngamePacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IngamePacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const IngamePacket* internal_default_instance() {
    return reinterpret_cast<const IngamePacket*>(
        &_IngamePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(IngamePacket& a, IngamePacket& b) { a.Swap(&b); }
  inline void Swap(IngamePacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IngamePacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IngamePacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IngamePacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IngamePacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IngamePacket& from) { IngamePacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IngamePacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.IngamePacket"; }

 protected:
  explicit IngamePacket(::google::protobuf::Arena* arena);
  IngamePacket(::google::protobuf::Arena* arena, const IngamePacket& from);
  IngamePacket(::google::protobuf::Arena* arena, IngamePacket&& from) noexcept
      : IngamePacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 1,
    kRoomIdFieldNumber = 2,
    kDataFieldNumber = 4,
    kMethodFieldNumber = 3,
  };
  // bytes sessionId = 1;
  void clear_sessionid() ;
  const std::string& sessionid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sessionid(Arg_&& arg, Args_... args);
  std::string* mutable_sessionid();
  PROTOBUF_NODISCARD std::string* release_sessionid();
  void set_allocated_sessionid(std::string* value);

  private:
  const std::string& _internal_sessionid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sessionid(
      const std::string& value);
  std::string* _internal_mutable_sessionid();

  public:
  // bytes roomId = 2;
  void clear_roomid() ;
  const std::string& roomid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_roomid(Arg_&& arg, Args_... args);
  std::string* mutable_roomid();
  PROTOBUF_NODISCARD std::string* release_roomid();
  void set_allocated_roomid(std::string* value);

  private:
  const std::string& _internal_roomid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_roomid(
      const std::string& value);
  std::string* _internal_mutable_roomid();

  public:
  // bytes data = 4;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // .Protocol.IngameType method = 3;
  void clear_method() ;
  ::Protocol::IngameType method() const;
  void set_method(::Protocol::IngameType value);

  private:
  ::Protocol::IngameType _internal_method() const;
  void _internal_set_method(::Protocol::IngameType value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.IngamePacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const IngamePacket& from_msg);
    ::google::protobuf::internal::ArenaStringPtr sessionid_;
    ::google::protobuf::internal::ArenaStringPtr roomid_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    int method_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class AuthenticationPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.AuthenticationPacket) */ {
 public:
  inline AuthenticationPacket() : AuthenticationPacket(nullptr) {}
  ~AuthenticationPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AuthenticationPacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AuthenticationPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AuthenticationPacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline AuthenticationPacket(const AuthenticationPacket& from) : AuthenticationPacket(nullptr, from) {}
  inline AuthenticationPacket(AuthenticationPacket&& from) noexcept
      : AuthenticationPacket(nullptr, std::move(from)) {}
  inline AuthenticationPacket& operator=(const AuthenticationPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthenticationPacket& operator=(AuthenticationPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthenticationPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuthenticationPacket* internal_default_instance() {
    return reinterpret_cast<const AuthenticationPacket*>(
        &_AuthenticationPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(AuthenticationPacket& a, AuthenticationPacket& b) { a.Swap(&b); }
  inline void Swap(AuthenticationPacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthenticationPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthenticationPacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AuthenticationPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AuthenticationPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AuthenticationPacket& from) { AuthenticationPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AuthenticationPacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.AuthenticationPacket"; }

 protected:
  explicit AuthenticationPacket(::google::protobuf::Arena* arena);
  AuthenticationPacket(::google::protobuf::Arena* arena, const AuthenticationPacket& from);
  AuthenticationPacket(::google::protobuf::Arena* arena, AuthenticationPacket&& from) noexcept
      : AuthenticationPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 1,
    kRoomIdFieldNumber = 2,
    kDataFieldNumber = 4,
    kMethodFieldNumber = 3,
  };
  // bytes sessionId = 1;
  void clear_sessionid() ;
  const std::string& sessionid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sessionid(Arg_&& arg, Args_... args);
  std::string* mutable_sessionid();
  PROTOBUF_NODISCARD std::string* release_sessionid();
  void set_allocated_sessionid(std::string* value);

  private:
  const std::string& _internal_sessionid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sessionid(
      const std::string& value);
  std::string* _internal_mutable_sessionid();

  public:
  // bytes roomId = 2;
  void clear_roomid() ;
  const std::string& roomid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_roomid(Arg_&& arg, Args_... args);
  std::string* mutable_roomid();
  PROTOBUF_NODISCARD std::string* release_roomid();
  void set_allocated_roomid(std::string* value);

  private:
  const std::string& _internal_roomid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_roomid(
      const std::string& value);
  std::string* _internal_mutable_roomid();

  public:
  // bytes data = 4;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // .Protocol.AuthenticationType method = 3;
  void clear_method() ;
  ::Protocol::AuthenticationType method() const;
  void set_method(::Protocol::AuthenticationType value);

  private:
  ::Protocol::AuthenticationType _internal_method() const;
  void _internal_set_method(::Protocol::AuthenticationType value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.AuthenticationPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AuthenticationPacket& from_msg);
    ::google::protobuf::internal::ArenaStringPtr sessionid_;
    ::google::protobuf::internal::ArenaStringPtr roomid_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    int method_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Packet

// .Protocol.PacketType type = 1;
inline void Packet::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::Protocol::PacketType Packet::type() const {
  // @@protoc_insertion_point(field_get:Protocol.Packet.type)
  return _internal_type();
}
inline void Packet::set_type(::Protocol::PacketType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Protocol.Packet.type)
}
inline ::Protocol::PacketType Packet::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::PacketType>(_impl_.type_);
}
inline void Packet::_internal_set_type(::Protocol::PacketType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// bytes data = 2;
inline void Packet::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& Packet::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.Packet.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Packet::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.Packet.data)
}
inline std::string* Packet::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Protocol.Packet.data)
  return _s;
}
inline const std::string& Packet::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void Packet::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* Packet::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* Packet::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.Packet.data)
  return _impl_.data_.Release();
}
inline void Packet::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.Packet.data)
}

// -------------------------------------------------------------------

// IngamePacket

// bytes sessionId = 1;
inline void IngamePacket::clear_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.ClearToEmpty();
}
inline const std::string& IngamePacket::sessionid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.IngamePacket.sessionId)
  return _internal_sessionid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void IngamePacket::set_sessionid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.IngamePacket.sessionId)
}
inline std::string* IngamePacket::mutable_sessionid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sessionid();
  // @@protoc_insertion_point(field_mutable:Protocol.IngamePacket.sessionId)
  return _s;
}
inline const std::string& IngamePacket::_internal_sessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sessionid_.Get();
}
inline void IngamePacket::_internal_set_sessionid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.Set(value, GetArena());
}
inline std::string* IngamePacket::_internal_mutable_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sessionid_.Mutable( GetArena());
}
inline std::string* IngamePacket::release_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.IngamePacket.sessionId)
  return _impl_.sessionid_.Release();
}
inline void IngamePacket::set_allocated_sessionid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sessionid_.IsDefault()) {
    _impl_.sessionid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.IngamePacket.sessionId)
}

// bytes roomId = 2;
inline void IngamePacket::clear_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.ClearToEmpty();
}
inline const std::string& IngamePacket::roomid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.IngamePacket.roomId)
  return _internal_roomid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void IngamePacket::set_roomid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.IngamePacket.roomId)
}
inline std::string* IngamePacket::mutable_roomid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_roomid();
  // @@protoc_insertion_point(field_mutable:Protocol.IngamePacket.roomId)
  return _s;
}
inline const std::string& IngamePacket::_internal_roomid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomid_.Get();
}
inline void IngamePacket::_internal_set_roomid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.Set(value, GetArena());
}
inline std::string* IngamePacket::_internal_mutable_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.roomid_.Mutable( GetArena());
}
inline std::string* IngamePacket::release_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.IngamePacket.roomId)
  return _impl_.roomid_.Release();
}
inline void IngamePacket::set_allocated_roomid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.roomid_.IsDefault()) {
    _impl_.roomid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.IngamePacket.roomId)
}

// .Protocol.IngameType method = 3;
inline void IngamePacket::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = 0;
}
inline ::Protocol::IngameType IngamePacket::method() const {
  // @@protoc_insertion_point(field_get:Protocol.IngamePacket.method)
  return _internal_method();
}
inline void IngamePacket::set_method(::Protocol::IngameType value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:Protocol.IngamePacket.method)
}
inline ::Protocol::IngameType IngamePacket::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::IngameType>(_impl_.method_);
}
inline void IngamePacket::_internal_set_method(::Protocol::IngameType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = value;
}

// bytes data = 4;
inline void IngamePacket::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& IngamePacket::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.IngamePacket.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void IngamePacket::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.IngamePacket.data)
}
inline std::string* IngamePacket::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Protocol.IngamePacket.data)
  return _s;
}
inline const std::string& IngamePacket::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void IngamePacket::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* IngamePacket::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* IngamePacket::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.IngamePacket.data)
  return _impl_.data_.Release();
}
inline void IngamePacket::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.IngamePacket.data)
}

// -------------------------------------------------------------------

// AuthenticationPacket

// bytes sessionId = 1;
inline void AuthenticationPacket::clear_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.ClearToEmpty();
}
inline const std::string& AuthenticationPacket::sessionid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.AuthenticationPacket.sessionId)
  return _internal_sessionid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AuthenticationPacket::set_sessionid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.AuthenticationPacket.sessionId)
}
inline std::string* AuthenticationPacket::mutable_sessionid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sessionid();
  // @@protoc_insertion_point(field_mutable:Protocol.AuthenticationPacket.sessionId)
  return _s;
}
inline const std::string& AuthenticationPacket::_internal_sessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sessionid_.Get();
}
inline void AuthenticationPacket::_internal_set_sessionid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.Set(value, GetArena());
}
inline std::string* AuthenticationPacket::_internal_mutable_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sessionid_.Mutable( GetArena());
}
inline std::string* AuthenticationPacket::release_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.AuthenticationPacket.sessionId)
  return _impl_.sessionid_.Release();
}
inline void AuthenticationPacket::set_allocated_sessionid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sessionid_.IsDefault()) {
    _impl_.sessionid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.AuthenticationPacket.sessionId)
}

// bytes roomId = 2;
inline void AuthenticationPacket::clear_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.ClearToEmpty();
}
inline const std::string& AuthenticationPacket::roomid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.AuthenticationPacket.roomId)
  return _internal_roomid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AuthenticationPacket::set_roomid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.AuthenticationPacket.roomId)
}
inline std::string* AuthenticationPacket::mutable_roomid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_roomid();
  // @@protoc_insertion_point(field_mutable:Protocol.AuthenticationPacket.roomId)
  return _s;
}
inline const std::string& AuthenticationPacket::_internal_roomid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.roomid_.Get();
}
inline void AuthenticationPacket::_internal_set_roomid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.Set(value, GetArena());
}
inline std::string* AuthenticationPacket::_internal_mutable_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.roomid_.Mutable( GetArena());
}
inline std::string* AuthenticationPacket::release_roomid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.AuthenticationPacket.roomId)
  return _impl_.roomid_.Release();
}
inline void AuthenticationPacket::set_allocated_roomid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.roomid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.roomid_.IsDefault()) {
    _impl_.roomid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.AuthenticationPacket.roomId)
}

// .Protocol.AuthenticationType method = 3;
inline void AuthenticationPacket::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = 0;
}
inline ::Protocol::AuthenticationType AuthenticationPacket::method() const {
  // @@protoc_insertion_point(field_get:Protocol.AuthenticationPacket.method)
  return _internal_method();
}
inline void AuthenticationPacket::set_method(::Protocol::AuthenticationType value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:Protocol.AuthenticationPacket.method)
}
inline ::Protocol::AuthenticationType AuthenticationPacket::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::AuthenticationType>(_impl_.method_);
}
inline void AuthenticationPacket::_internal_set_method(::Protocol::AuthenticationType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = value;
}

// bytes data = 4;
inline void AuthenticationPacket::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& AuthenticationPacket::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.AuthenticationPacket.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AuthenticationPacket::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.AuthenticationPacket.data)
}
inline std::string* AuthenticationPacket::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Protocol.AuthenticationPacket.data)
  return _s;
}
inline const std::string& AuthenticationPacket::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void AuthenticationPacket::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* AuthenticationPacket::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* AuthenticationPacket::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.AuthenticationPacket.data)
  return _impl_.data_.Release();
}
inline void AuthenticationPacket::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.AuthenticationPacket.data)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::PacketType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::PacketType>() {
  return ::Protocol::PacketType_descriptor();
}
template <>
struct is_proto_enum<::Protocol::IngameType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::IngameType>() {
  return ::Protocol::IngameType_descriptor();
}
template <>
struct is_proto_enum<::Protocol::AuthenticationType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::AuthenticationType>() {
  return ::Protocol::AuthenticationType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Packet_2eproto_2epb_2eh
