:: Generated by AI

@echo off
setlocal enabledelayedexpansion

:: vcpkg에서 설치한 protoc.exe 경로 탐색
set "VCPKG_PROTOC=C:\vcpkg\installed\x64-windows\tools\protobuf\protoc.exe"

echo Using protoc: %VCPKG_PROTOC%

:: 경로 설정
set "PROTO_SRC=."
set "SERVER_HEADER=..\server\src\header"
set "SERVER_SOURCE=..\server\src\sources"
set "CLIENT_HEADER=..\client\src\header"
set "CLIENT_SOURCE=..\client\src\sources"

:: proto 파일 컴파일
for %%f in (%PROTO_SRC%\*.proto) do (
    echo Processing %%f...

    :: 서버용 생성
    "%VCPKG_PROTOC%" --proto_path="%PROTO_SRC%" --cpp_out="%SERVER_HEADER%" "%%f"
    if exist "%SERVER_HEADER%\*.pb.cc" (
        move /y "%SERVER_HEADER%\*.pb.cc" "%SERVER_SOURCE%\"
    )

    :: 클라이언트용 생성
    "%VCPKG_PROTOC%" --proto_path="%PROTO_SRC%" --cpp_out="%CLIENT_HEADER%" "%%f"
    if exist "%CLIENT_HEADER%\*.pb.cc" (
        move /y "%CLIENT_HEADER%\*.pb.cc" "%CLIENT_SOURCE%\"
    )

    echo Generated headers and sources from %%f
)

echo All proto files generated!
pause
