#!/bin/zsh

# Generated by AI
# vcpkg에서 설치한 protoc 경로 탐색 (현재 시스템에 맞게)
VCPKG_PROTOC=""
if [[ -f "../server/build/vcpkg_installed/arm64-osx/tools/protobuf/protoc" ]]; then
  VCPKG_PROTOC="../server/build/vcpkg_installed/arm64-osx/tools/protobuf/protoc"
elif [[ -f "../server/build/vcpkg_installed/x64-osx/tools/protobuf/protoc" ]]; then
  VCPKG_PROTOC="../server/build/vcpkg_installed/x64-osx/tools/protobuf/protoc"
else
  VCPKG_PROTOC=$(which protoc)
  echo "Warning: vcpkg protoc not found. Using system protoc: $VCPKG_PROTOC"
fi

echo "Using protoc: $VCPKG_PROTOC"

# proto 소스 디렉토리
PROTO_SRC="../proto" 

# 서버 헤더 및 소스 경로
SERVER_HEADER="../server/src/header"
SERVER_SOURCE="../server/src/sources"

# 클라이언트 헤더 및 소스 경로
CLIENT_HEADER="../client/src/header"
CLIENT_SOURCE="../client/src/sources"

# proto 파일 찾기
PROTO_FILES=($PROTO_SRC/**/*.proto)

if [[ ${#PROTO_FILES[@]} -eq 0 ]]; then
  echo "No .proto files found in $PROTO_SRC"
  exit 1
fi

# 각 proto 파일 컴파일
for proto in $PROTO_FILES; do
  # 서버용 생성
  $VCPKG_PROTOC --proto_path=$PROTO_SRC \
         --cpp_out=$SERVER_HEADER \
         $proto
  
  # .cc 파일을 sources로 이동
  mv $SERVER_HEADER/*.pb.cc $SERVER_SOURCE/
  
  # 클라이언트용 생성
  $VCPKG_PROTOC --proto_path=$PROTO_SRC \
         --cpp_out=$CLIENT_HEADER \
         $proto
  
  # .cc 파일을 sources로 이동
  mv $CLIENT_HEADER/*.pb.cc $CLIENT_SOURCE/
  
  echo "Generated headers and sources from $proto"
done

echo "All proto files generated!"
