syntax = "proto3";

package Protocol;

enum PacketType {
    // status response
    PacketOk = 0;
    InvalidData = 1;
    ErrorOccured = 2;

    // Tcp
    PortHandshake = 100;
    InfoHandshake = 101;
    Ping = 102;
    Match = 103;

    // Udp
    Ingame = 200;
    Authentication = 201;
}

enum IngameType {
    IngameOk = 0;
    Move = 1;
    Jump = 2;
    Shoot = 3;
    Hit = 4;
}

enum MatchmakingType {
    MatchmakingOk = 0;
    Request = 1;
    Success = 2;
    Failed = 3;

    Waiting = 4;
    Matched = 5; 
}

enum AuthenticationType {
    AuthenticationOk = 0;
    UdpHolePunching = 1;
}

message Packet {
    PacketType type = 1;
    bytes data = 2;
}

message Matchmaking {
    MatchmakingType type = 1;
    bytes sessionId = 2;
    optional bytes roomId = 3;
}

message IngamePacket {
   bytes sessionId = 1;
   bytes roomId = 2; 
   IngameType method = 3;
   bytes data = 4;
} 

message AuthenticationPacket {
    bytes sessionId = 1;
    bytes roomId = 2;
    AuthenticationType method = 3;
    bytes data = 4;
}