syntax = "proto3";

package Protocol;

enum PacketType {
    // status response
    Ok = 0;
    InvalidData = 1;
    ErrorOccured = 2;

    // Tcp
    PortHandshake = 100;
    InfoHandshake = 101;
    Ping = 102;

    // Udp
    Ingame = 200;
    Autentication = 201;
}

enum IngameType {
    IngameOk = 0;
    Move = 1;
    Jump = 2;
    Shoot = 3;
    Hit = 4;
}

enum AuthenticationType {
    AuthenticationOk = 0;
}

message Packet{
    PacketType type = 1;
    bytes data = 2;
}

message IngamePacket {
   bytes sessionId = 2;
   bytes roomId = 1; 
   IngameType method = 3;
   bytes data = 4;
} 

//message AutenticationPacket {
//}