<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>AuthServer</RootNamespace>
        <AssemblyName>AuthServer</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.28.2" />
      <PackageReference Include="Grpc.Tools" Version="2.67.0">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.6" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
      <PackageReference Include="Scalar.AspNetCore" Version="2.14.1" />
      <PackageReference Include="Serilog" Version="4.3.1" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
      <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="..\proto\Internal.proto" GrpcServices="None" Link="Protos\Internal.proto" />
    </ItemGroup>
</Project>